import EvmCompiler.Public
import EvmCompiler.Solidity
import EvmCompiler.BackendCli
import EvmCompiler.Compiler.StackArtifact
import EvmCompiler.Compiler.OpenInteractionComposition
import EvmCompiler.Functions.StackPressureNormalizationProgram
import EvmCompiler.Functions.StackLowering
import EvmCompiler.Functions.StackRecursivePreservation
import EvmCompiler.Expressions.InteractionPreservation
import EvmCompiler.Expressions.TargetFuelSafety
import EvmCompiler.Structured.InteractionTerminalPreservation
import EvmCompiler.Structured.InteractionFuelSafety
import EvmCompiler.Structured.TypedCfgPreservation
import EvmCompiler.TypedCfg.InteractionPreservation
import EvmCompiler.TypedCfg.InteractionPrefixPreservation
import EvmCompiler.TypedCfg.InteractionFuelSafety
import EvmCompiler.Assembly.InteractionBytecode
import EvmCompiler.Assembly.InteractionFuelSafety
import EvmCompiler.Assembly.Compact
import EvmCompiler.Solidity.VerifiedStackObjectArtifact
import EvmCompiler.Solidity.RawAstPublic
import EvmCompiler.Solidity.RawAstEndToEnd
import EvmCompiler.Yul.FunctionsInteractionProgram
import EvmCompiler.Yul.EndToEnd

/-!
Production verification root for the optimized-solc-Yul stack-only backend.

Importing this module checks the complete production dependency closure. The
declarations below pin the adjacent preservation spine and its public endpoint.
-/

#check EvmCompiler.Functions.StackPressureNormalization.Program.normalize
#check EvmCompiler.Functions.StackLowering.lowerProgram?
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyForward
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyTerminal
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyFinished
#check EvmCompiler.Functions.StackRecursivePreservation.ProgramTargetFinished
#check EvmCompiler.Assembly.InteractionFuelSafety.PrimOp.openStep
#check EvmCompiler.Structured.InteractionFuelSafety.Code.openRun
#check EvmCompiler.Expressions.TargetFuelSafety.expressionOpenRun
#check EvmCompiler.Compiler.StackArtifact.compile?_parts
#check EvmCompiler.Compiler.StackArtifact.compile?_decodingCorrect
#check EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackCodeArtifactIn?_parts
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_decodingCorrect
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_sentinelImage
#check EvmCompiler.Solidity.Frontend.Stmt.toYul?_functionDef_erases
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_some
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_parts
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_objectParts
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_itemRefsPreserveOrder
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_noRawClzCall
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_clzExpansionOk
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_hoistedFunctionsRetained
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_frontendValidated
#check EvmCompiler.Solidity.RawAst.Elab.clzHelperFunctionDef_toYul?_some
#check EvmCompiler.Solidity.RawAst.Elab.elaborateCode_parts
#check EvmCompiler.Solidity.RawAst.Elab.elaborateCode_clzHelper_mem
#check EvmCompiler.Solidity.RawAst.Elab.elaborateCode_clzHelper_shape
#check EvmCompiler.Solidity.RawAst.Elab.elaborateCode_clzHelper_toYul?_some
#check EvmCompiler.Solidity.RawAst.Elab.elaborateCode_hoistedFunction_mem
#check EvmCompiler.Solidity.RawAst.Raw.Object.elaborate?_clzExpansionOk
#check EvmCompiler.Solidity.RawAst.Raw.Object.elaborate?_hoistedFunctionsRetained
#check EvmCompiler.Solidity.RawAst.Raw.Object.elaboratePreservingOrder?_parts
#check EvmCompiler.Solidity.RawAst.Raw.Object.elaboratePreservingOrder?_noRawClzCall
#check EvmCompiler.Solidity.RawAst.Raw.Object.elaboratePreservingOrder?_frontendValidated
#check EvmCompiler.Solidity.RawAst.Raw.Object.elaborate?_parts
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_parts
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_objectParts
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_itemRefsPreserveOrder
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_noRawClzCall
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_clzExpansionOk
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_hoistedFunctionsRetained
#check EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_frontendValidated
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_decoded
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_valid
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_rawParts
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_itemRefsPreserveOrder
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_noRawClzCall
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_clzExpansionOk
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_hoistedFunctionsRetained
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_frontendValidated
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_decodingCorrect
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_valid
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_rawParts
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_itemRefsPreserveOrder
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_noRawClzCall
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_clzExpansionOk
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_hoistedFunctionsRetained
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_frontendValidated
#check EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_decodingCorrect
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecode
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecodeFinished
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackExpressionsTerminal
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackExpressionsForward
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackStructuredForward
#check EvmCompiler.Structured.InteractionTruncationOwnerPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_forward
#check EvmCompiler.Structured.InteractionTruncationOwnerPreservation.OpenOutcome.GeneratedProgram.main_prefix_forward
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackTypedCfgForward
#check EvmCompiler.Simulation.Interaction.ForwardRel.of_executes_or_follows
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_follows_of_le
#check EvmCompiler.TypedCfg.InteractionPrefixPreservation.Program.compileCertified?_entry_openRunNPrefix_assembly_forward
#check EvmCompiler.TypedCfg.InteractionFuelSafety.Program.openRunNResultWithStop
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackAssemblyPrefixForward
#check EvmCompiler.Assembly.Compact.InteractionSemantics.compile?_source_openRunNResult_branch
#check EvmCompiler.Compiler.OpenInteractionComposition.stackAssemblyPrefixToCompactBytecode
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecodeForwardPublic
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.UniformExecPreservesUnder.with_runtime_errors_and_truncation
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackExpressionsFinished
#check EvmCompiler.Compiler.OpenInteractionComposition.stackExpressionsToStructuredFinished
#check EvmCompiler.Compiler.OpenInteractionComposition.yulNormalizedStackToAssemblySourceFinished
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecodeFinishedPublic
#check EvmCompiler.Compiler.OpenInteractionComposition.stackExpressionsToStructuredStopped
#check EvmCompiler.Structured.InteractionTerminalPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_finished
#check EvmCompiler.TypedCfg.InteractionPreservation.Program.compileCertified?_entry_openRunN_assembly_finished_rel
#check EvmCompiler.Compiler.OpenInteractionComposition.structuredToAssemblySourceFinished
#check EvmCompiler.Assembly.Compact.InteractionSemantics.compile?_source_openRunNResult_finished_rel
#check EvmCompiler.Compiler.OpenInteractionComposition.stackAssemblyToCompactBytecodeFinished
#check EvmCompiler.Compiler.OpenInteractionComposition.yulNormalizedStackToAssemblySource
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackCodeToRawBytecode
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinished
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinishedLegacy

#print axioms EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#print axioms EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyForward
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackStructuredForward
#print axioms EvmCompiler.Structured.InteractionTruncationOwnerPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_forward
#print axioms EvmCompiler.Structured.InteractionTruncationOwnerPreservation.OpenOutcome.GeneratedProgram.main_prefix_forward
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackTypedCfgForward
#print axioms EvmCompiler.TypedCfg.InteractionPrefixPreservation.Program.compileCertified?_entry_openRunNPrefix_assembly_forward
#print axioms EvmCompiler.TypedCfg.InteractionFuelSafety.Program.openRunNResultWithStop
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackAssemblyPrefixForward
#print axioms EvmCompiler.Assembly.Compact.InteractionSemantics.compile?_source_openRunNResult_branch
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.stackAssemblyPrefixToCompactBytecode
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecodeForwardPublic
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.UniformExecPreservesUnder.with_runtime_errors_and_truncation
#print axioms EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyFinished
#print axioms EvmCompiler.Assembly.InteractionFuelSafety.PrimOp.openStep
#print axioms EvmCompiler.Structured.InteractionFuelSafety.Code.openRun
#print axioms EvmCompiler.Expressions.TargetFuelSafety.expressionOpenRun
#print axioms EvmCompiler.Compiler.StackArtifact.compile?_decodingCorrect
#print axioms EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_sentinelImage
#print axioms EvmCompiler.Solidity.Frontend.Stmt.toYul?_functionDef_erases
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_some
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_parts
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_objectParts
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_itemRefsPreserveOrder
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_noRawClzCall
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_clzExpansionOk
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_hoistedFunctionsRetained
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIr?_frontendValidated
#print axioms EvmCompiler.Solidity.RawAst.Elab.clzHelperFunctionDef_toYul?_some
#print axioms EvmCompiler.Solidity.RawAst.Elab.elaborateCode_parts
#print axioms EvmCompiler.Solidity.RawAst.Elab.elaborateCode_clzHelper_mem
#print axioms EvmCompiler.Solidity.RawAst.Elab.elaborateCode_clzHelper_shape
#print axioms EvmCompiler.Solidity.RawAst.Elab.elaborateCode_clzHelper_toYul?_some
#print axioms EvmCompiler.Solidity.RawAst.Elab.elaborateCode_hoistedFunction_mem
#print axioms EvmCompiler.Solidity.RawAst.Raw.Object.elaborate?_clzExpansionOk
#print axioms EvmCompiler.Solidity.RawAst.Raw.Object.elaborate?_hoistedFunctionsRetained
#print axioms EvmCompiler.Solidity.RawAst.Raw.Object.elaboratePreservingOrder?_parts
#print axioms EvmCompiler.Solidity.RawAst.Raw.Object.elaboratePreservingOrder?_noRawClzCall
#print axioms EvmCompiler.Solidity.RawAst.Raw.Object.elaboratePreservingOrder?_frontendValidated
#print axioms EvmCompiler.Solidity.RawAst.Raw.Object.elaborate?_parts
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_parts
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_objectParts
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_itemRefsPreserveOrder
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_noRawClzCall
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_clzExpansionOk
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_hoistedFunctionsRetained
#print axioms EvmCompiler.Solidity.RawAst.decodeAndElaborateSolcIrJson_frontendValidated
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_decoded
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_valid
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_rawParts
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_itemRefsPreserveOrder
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_noRawClzCall
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_clzExpansionOk
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_hoistedFunctionsRetained
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_frontendValidated
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIr?_decodingCorrect
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_valid
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_rawParts
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_itemRefsPreserveOrder
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_noRawClzCall
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_clzExpansionOk
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_hoistedFunctionsRetained
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_frontendValidated
#print axioms EvmCompiler.Solidity.RawAst.compileArtifactFromRawSolcIrWithLinkerSymbols?_decodingCorrect
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecode
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecodeFinished
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackExpressionsFinished
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.yulNormalizedStackToAssemblySourceFinished
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecodeFinishedPublic
#print axioms EvmCompiler.Structured.InteractionTerminalPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_finished
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Program.compileCertified?_entry_openRunN_assembly_finished_rel
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.structuredToAssemblySourceFinished
#print axioms EvmCompiler.Assembly.Compact.InteractionSemantics.compile?_source_openRunNResult_finished_rel
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.stackAssemblyToCompactBytecodeFinished
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinished
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinishedLegacy
