import EvmCompiler.Public
import EvmCompiler.Solidity
import EvmCompiler.BackendCli
import EvmCompiler.Compiler.StackArtifact
import EvmCompiler.Compiler.OpenInteractionComposition
import EvmCompiler.Functions.StackPressureNormalizationProgram
import EvmCompiler.Functions.StackLowering
import EvmCompiler.Functions.StackRecursivePreservation
import EvmCompiler.Expressions.InteractionPreservation
import EvmCompiler.Structured.InteractionTerminalPreservation
import EvmCompiler.Structured.TypedCfgPreservation
import EvmCompiler.TypedCfg.InteractionPreservation
import EvmCompiler.Assembly.InteractionBytecode
import EvmCompiler.Assembly.Compact
import EvmCompiler.Solidity.VerifiedStackObjectArtifact
import EvmCompiler.Yul.FunctionsInteractionProgram
import EvmCompiler.Yul.EndToEnd

/-!
Production verification root for the optimized-solc-Yul stack-only backend.

Importing this module checks the complete production dependency closure. The
declarations below pin the adjacent preservation spine and its public endpoint.
-/

#check EvmCompiler.Functions.StackPressureNormalization.Program.normalize
#check EvmCompiler.Functions.StackLowering.lowerProgram?
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyTerminal
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyFinished
#check EvmCompiler.Compiler.StackArtifact.compile?_parts
#check EvmCompiler.Compiler.StackArtifact.compile?_decodingCorrect
#check EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackCodeArtifactIn?_parts
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_decodingCorrect
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackExpressionsTerminal
#check EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackExpressionsFinished
#check EvmCompiler.Compiler.OpenInteractionComposition.stackExpressionsToStructuredStopped
#check EvmCompiler.Structured.InteractionTerminalPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_finished
#check EvmCompiler.Compiler.OpenInteractionComposition.yulNormalizedStackToAssemblySource
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackCodeToRawBytecode
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode

#print axioms EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#print axioms EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyFinished
#print axioms EvmCompiler.Compiler.StackArtifact.compile?_decodingCorrect
#print axioms EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.yulToNormalizedStackExpressionsFinished
#print axioms EvmCompiler.Structured.InteractionTerminalPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_finished
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode
