import EvmCompiler

/-!
Generated by `scripts/solidity_to_yul_lean.py`.

Source: AaveV3InterestFallback.sol
Contract: AaveV3InterestFallback
Selected Yul object: AaveV3InterestFallback_47_deployed
-/

abbrev AstExpr := EvmYul.Yul.Ast.Expr
abbrev AstStmt := EvmYul.Yul.Ast.Stmt
abbrev AstFunctionDefinition := EvmYul.Yul.Ast.FunctionDefinition


def program : EvmCompiler.Yul.Program :=
  { contract :=
    { dispatcher := EvmYul.Yul.Ast.Stmt.Block [
        EvmYul.Yul.Ast.Stmt.Block [
            EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.MSTORE : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 64),
                EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 128)
              ]),
            EvmYul.Yul.Ast.Stmt.If (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.CALLVALUE : EvmYul.Operation EvmYul.OperationType.Yul)) []) [
                EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.REVERT : EvmYul.Operation EvmYul.OperationType.Yul)) [
                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0),
                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)
                  ])
              ],
            EvmYul.Yul.Ast.Stmt.Let [
                "_1"
              ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
            EvmYul.Yul.Ast.Stmt.Let [
                "var_result"
              ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
            EvmYul.Yul.Ast.Stmt.Switch (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.EQ : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.BYTE : EvmYul.Operation EvmYul.OperationType.Yul)) [
                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0),
                    EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.CALLDATALOAD : EvmYul.Operation EvmYul.OperationType.Yul)) [
                        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)
                      ]
                  ],
                EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1)
              ]) [
                (EvmYul.UInt256.ofNat 0, [
                      EvmYul.Yul.Ast.Stmt.Assign [
                          "var_result"
                        ] (EvmYul.Yul.Ast.Expr.Call (Sum.inr "fun_calculateCompoundedInterest") [
                          EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.TIMESTAMP : EvmYul.Operation EvmYul.OperationType.Yul)) []
                        ])
                    ])
              ] [
                EvmYul.Yul.Ast.Stmt.Let [
                    "var"
                  ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
                EvmYul.Yul.Ast.Stmt.Let [
                    "var_1"
                  ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "var"
                  ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "var_1"
                  ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "var_1"
                  ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
                EvmYul.Yul.Ast.Stmt.Let [
                    "expr"
                  ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "expr"
                  ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 31535998)),
                EvmYul.Yul.Ast.Stmt.Let [
                    "expr_1"
                  ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inr "fun_rayMul") [
                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
                  ])),
                EvmYul.Yul.Ast.Stmt.Let [
                    "r"
                  ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
                EvmYul.Yul.Ast.Stmt.Let [
                    "_2"
                  ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "_2"
                  ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "r"
                  ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
                    EvmYul.Yul.Ast.Expr.Var "expr_1",
                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 994519296000000)
                  ]),
                EvmYul.Yul.Ast.Stmt.Let [
                    "r_1"
                  ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
                    EvmYul.Yul.Ast.Expr.Call (Sum.inr "fun_rayMul") [
                        EvmYul.Yul.Ast.Expr.Var "r",
                        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
                      ],
                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 31536000)
                  ])),
                EvmYul.Yul.Ast.Stmt.Let [
                    "product"
                  ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "product"
                  ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 994519264464000)),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "_1"
                  ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
                EvmYul.Yul.Ast.Stmt.Let [
                    "expr_2"
                  ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inr "wrapping_div_uint256_389") [
                    EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                        EvmYul.Yul.Ast.Expr.Var "product",
                        EvmYul.Yul.Ast.Expr.Var "r"
                      ]
                  ])),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "var"
                  ] (EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_add_uint256") [
                    EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_add_uint256") [
                        EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_add_uint256_392") [
                            EvmYul.Yul.Ast.Expr.Call (Sum.inr "wrapping_div_uint256_391") [
                                EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
                                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 31536000)
                                  ]
                              ]
                          ],
                        EvmYul.Yul.Ast.Expr.Var "expr_2"
                      ],
                    EvmYul.Yul.Ast.Expr.Call (Sum.inr "wrapping_div_uint256") [
                        EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                            EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                                EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 31536000),
                                    EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 31535999)
                                  ],
                                EvmYul.Yul.Ast.Expr.Var "expr"
                              ],
                            EvmYul.Yul.Ast.Expr.Var "r_1"
                          ]
                      ]
                  ]),
                EvmYul.Yul.Ast.Stmt.Assign [
                    "var_result"
                  ] (EvmYul.Yul.Ast.Expr.Var "var")
              ],
            EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.MSTORE : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Var "_1",
                EvmYul.Yul.Ast.Expr.Var "var_result"
              ]),
            EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.RETURN : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Var "_1",
                EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 32)
              ])
          ]
      ]
      functions :=
        (∅ : Finmap (fun (_ : EvmYul.Yul.Ast.YulFunctionName) => AstFunctionDefinition))
    |>.insert "panic_error_0x11" (EvmYul.Yul.Ast.FunctionDefinition.Def [] [] [
    EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.MSTORE : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0),
        EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.SHL : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 224),
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1313373041)
          ]
      ]),
    EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.MSTORE : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 4),
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 17)
      ]),
    EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.REVERT : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0),
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 36)
      ])
  ])
    |>.insert "wrapping_div_uint256_389" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "x"
  ] [
    "r"
  ] [
    EvmYul.Yul.Ast.Stmt.Let [
        "_1"
      ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
    EvmYul.Yul.Ast.Stmt.Assign [
        "_1"
      ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
    EvmYul.Yul.Ast.Stmt.Assign [
        "r"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.SHR : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1),
        EvmYul.Yul.Ast.Expr.Var "x"
      ])
  ])
    |>.insert "wrapping_div_uint256" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "x"
  ] [
    "r"
  ] [
    EvmYul.Yul.Ast.Stmt.Let [
        "_1"
      ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
    EvmYul.Yul.Ast.Stmt.Assign [
        "_1"
      ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
    EvmYul.Yul.Ast.Stmt.Assign [
        "r"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "x",
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 6)
      ])
  ])
    |>.insert "wrapping_div_uint256_391" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "x"
  ] [
    "r"
  ] [
    EvmYul.Yul.Ast.Stmt.Let [
        "_1"
      ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
    EvmYul.Yul.Ast.Stmt.Assign [
        "_1"
      ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
    EvmYul.Yul.Ast.Stmt.Assign [
        "r"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "x",
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 31536000)
      ])
  ])
    |>.insert "checked_mul_uint256" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "x",
    "y"
  ] [
    "product"
  ] [
    EvmYul.Yul.Ast.Stmt.Assign [
        "product"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.MUL : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "x",
        EvmYul.Yul.Ast.Expr.Var "y"
      ]),
    EvmYul.Yul.Ast.Stmt.If (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ISZERO : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.OR : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ISZERO : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Var "x"
              ],
            EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.EQ : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Var "y",
                EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
                    EvmYul.Yul.Ast.Expr.Var "product",
                    EvmYul.Yul.Ast.Expr.Var "x"
                  ]
              ]
          ]
      ]) [
        EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inr "panic_error_0x11") [])
      ]
  ])
    |>.insert "checked_add_uint256_392" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "y"
  ] [
    "sum"
  ] [
    EvmYul.Yul.Ast.Stmt.Assign [
        "sum"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ADD : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1000000000000000000000000000),
        EvmYul.Yul.Ast.Expr.Var "y"
      ]),
    EvmYul.Yul.Ast.Stmt.If (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.GT : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1000000000000000000000000000),
        EvmYul.Yul.Ast.Expr.Var "sum"
      ]) [
        EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inr "panic_error_0x11") [])
      ]
  ])
    |>.insert "checked_add_uint256" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "x",
    "y"
  ] [
    "sum"
  ] [
    EvmYul.Yul.Ast.Stmt.Assign [
        "sum"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ADD : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "x",
        EvmYul.Yul.Ast.Expr.Var "y"
      ]),
    EvmYul.Yul.Ast.Stmt.If (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.GT : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "x",
        EvmYul.Yul.Ast.Expr.Var "sum"
      ]) [
        EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inr "panic_error_0x11") [])
      ]
  ])
    |>.insert "fun_calculateCompoundedInterest" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "var_currentTimestamp"
  ] [
    "var_"
  ] [
    EvmYul.Yul.Ast.Stmt.Assign [
        "var_"
      ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
    EvmYul.Yul.Ast.Stmt.Let [
        "diff"
      ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ADD : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "var_currentTimestamp",
        EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.NOT : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)
          ]
      ])),
    EvmYul.Yul.Ast.Stmt.If (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.GT : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "diff",
        EvmYul.Yul.Ast.Expr.Var "var_currentTimestamp"
      ]) [
        EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inr "panic_error_0x11") [])
      ],
    EvmYul.Yul.Ast.Stmt.If (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.EQ : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "var_currentTimestamp",
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1)
      ]) [
        EvmYul.Yul.Ast.Stmt.Assign [
            "var_"
          ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1000000000000000000000000000)),
        EvmYul.Yul.Ast.Stmt.Leave
      ],
    EvmYul.Yul.Ast.Stmt.Let [
        "expr"
      ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ADD : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "var_currentTimestamp",
        EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.NOT : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1)
          ]
      ])),
    EvmYul.Yul.Ast.Stmt.Let [
        "expr_1"
      ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
    EvmYul.Yul.Ast.Stmt.Switch (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.GT : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "diff",
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 2)
      ]) [
        (EvmYul.UInt256.ofNat 0, [
              EvmYul.Yul.Ast.Stmt.Assign [
                  "expr_1"
                ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))
            ])
      ] [
        EvmYul.Yul.Ast.Stmt.Assign [
            "expr_1"
          ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ADD : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Var "var_currentTimestamp",
            EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.NOT : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 2)
              ]
          ])
      ],
    EvmYul.Yul.Ast.Stmt.Let [
        "x"
      ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inr "fun_rayMul") [
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
      ])),
    EvmYul.Yul.Ast.Stmt.Let [
        "r"
      ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
    EvmYul.Yul.Ast.Stmt.Let [
        "_1"
      ] (some (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0))),
    EvmYul.Yul.Ast.Stmt.Assign [
        "_1"
      ] (EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)),
    EvmYul.Yul.Ast.Stmt.Assign [
        "r"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Var "x",
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 994519296000000)
      ]),
    EvmYul.Yul.Ast.Stmt.Let [
        "r_1"
      ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Call (Sum.inr "fun_rayMul") [
            EvmYul.Yul.Ast.Expr.Var "r",
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
          ],
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 31536000)
      ])),
    EvmYul.Yul.Ast.Stmt.Let [
        "expr_2"
      ] (some (EvmYul.Yul.Ast.Expr.Call (Sum.inr "wrapping_div_uint256_389") [
        EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
            EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                EvmYul.Yul.Ast.Expr.Var "diff",
                EvmYul.Yul.Ast.Expr.Var "expr"
              ],
            EvmYul.Yul.Ast.Expr.Var "r"
          ]
      ])),
    EvmYul.Yul.Ast.Stmt.Assign [
        "var_"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_add_uint256") [
        EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_add_uint256") [
            EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_add_uint256_392") [
                EvmYul.Yul.Ast.Expr.Call (Sum.inr "wrapping_div_uint256_391") [
                    EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
                        EvmYul.Yul.Ast.Expr.Var "diff"
                      ]
                  ]
              ],
            EvmYul.Yul.Ast.Expr.Var "expr_2"
          ],
        EvmYul.Yul.Ast.Expr.Call (Sum.inr "wrapping_div_uint256") [
            EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                    EvmYul.Yul.Ast.Expr.Call (Sum.inr "checked_mul_uint256") [
                        EvmYul.Yul.Ast.Expr.Var "diff",
                        EvmYul.Yul.Ast.Expr.Var "expr"
                      ],
                    EvmYul.Yul.Ast.Expr.Var "expr_1"
                  ],
                EvmYul.Yul.Ast.Expr.Var "r_1"
              ]
          ]
      ])
  ])
    |>.insert "fun_rayMul" (EvmYul.Yul.Ast.FunctionDefinition.Def [
    "var_a",
    "var_b"
  ] [
    "var_c"
  ] [
    EvmYul.Yul.Ast.Stmt.If (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ISZERO : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.OR : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ISZERO : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Var "var_b"
              ],
            EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ISZERO : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.GT : EvmYul.Operation EvmYul.OperationType.Yul)) [
                    EvmYul.Yul.Ast.Expr.Var "var_a",
                    EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
                        EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.NOT : EvmYul.Operation EvmYul.OperationType.Yul)) [
                            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 500000000000000000000000000)
                          ],
                        EvmYul.Yul.Ast.Expr.Var "var_b"
                      ]
                  ]
              ]
          ]
      ]) [
        EvmYul.Yul.Ast.Stmt.ExprStmtCall (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.REVERT : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0),
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 0)
          ])
      ],
    EvmYul.Yul.Ast.Stmt.Assign [
        "var_c"
      ] (EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.DIV : EvmYul.Operation EvmYul.OperationType.Yul)) [
        EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.ADD : EvmYul.Operation EvmYul.OperationType.Yul)) [
            EvmYul.Yul.Ast.Expr.Call (Sum.inl (EvmYul.Operation.MUL : EvmYul.Operation EvmYul.OperationType.Yul)) [
                EvmYul.Yul.Ast.Expr.Var "var_a",
                EvmYul.Yul.Ast.Expr.Var "var_b"
              ],
            EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 500000000000000000000000000)
          ],
        EvmYul.Yul.Ast.Expr.Lit (EvmYul.UInt256.ofNat 1000000000000000000000000000)
      ])
  ])
    }
  }

noncomputable def programCheckedAssembly : Option EvmCompiler.Assembly.Program :=
  EvmCompiler.Yul.Program.compileSolcChecked? program

noncomputable def programTarget : Option EvmCompiler.Assembly.TargetProgram := do
  let asm ← programCheckedAssembly
  EvmCompiler.Assembly.compile? asm

noncomputable def programBytecode : Option ByteArray := do
  let target ← programTarget
  some (EvmCompiler.Assembly.Bytecode.encodeTarget target)
