import EvmCompiler.Solidity.Frontend
import EvmCompiler.Functions.CallAwareSpill
import EvmCompiler.Yul.Preservation
import EvmCompiler.Assembly.Bytecode

/-!
Generated by `scripts/solidity_to_yul_lean.py --format lean-ir`.

Source: AaveV3InterestFallback.sol
Contract: AaveV3InterestFallback
Selected Yul object: AaveV3InterestFallback_47_deployed
-/


def program : EvmCompiler.Solidity.Frontend.Program :=
  EvmCompiler.Solidity.Frontend.Program.mk "AaveV3InterestFallback.sol" "AaveV3InterestFallback" (EvmCompiler.Solidity.Frontend.Object.mk "AaveV3InterestFallback_47_deployed" [
    EvmCompiler.Solidity.Frontend.Stmt.block [
        EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "mstore" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 64),
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 128)
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.ifThen (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "callvalue" []) [
            EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "revert" [
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0),
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)
              ])
          ],
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "_1"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "var_result"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.switch (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "eq" [
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "byte" [
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0),
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "calldataload" [
                    EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)
                  ]
              ],
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1)
          ]) [
            (EvmCompiler.Solidity.Frontend.SwitchCaseValue.word (EvmYul.UInt256.ofNat 0), [
                  EvmCompiler.Solidity.Frontend.Stmt.assign [
                      "var_result"
                    ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "fun_calculateCompoundedInterest" [
                      EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "timestamp" []
                    ])
                ])
          ] [
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "var"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "var_1"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "var"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "var_1"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "var_1"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "expr"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "expr"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 31535998)),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "expr_1"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "fun_rayMul" [
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
              ])),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "r"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "_2"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "_2"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "r"
              ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
                EvmCompiler.Solidity.Frontend.Expr.var "expr_1",
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 994519296000000)
              ]),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "r_1"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "fun_rayMul" [
                    EvmCompiler.Solidity.Frontend.Expr.var "r",
                    EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
                  ],
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 31536000)
              ])),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "product"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "product"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 994519264464000)),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "_1"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
            EvmCompiler.Solidity.Frontend.Stmt.letDecl [
                "expr_2"
              ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "wrapping_div_uint256_389" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                    EvmCompiler.Solidity.Frontend.Expr.var "product",
                    EvmCompiler.Solidity.Frontend.Expr.var "r"
                  ]
              ])),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "var"
              ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_add_uint256" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_add_uint256" [
                    EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_add_uint256_392" [
                        EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "wrapping_div_uint256_391" [
                            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
                                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 31536000)
                              ]
                          ]
                      ],
                    EvmCompiler.Solidity.Frontend.Expr.var "expr_2"
                  ],
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "wrapping_div_uint256" [
                    EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                        EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 31536000),
                                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 31535999)
                              ],
                            EvmCompiler.Solidity.Frontend.Expr.var "expr"
                          ],
                        EvmCompiler.Solidity.Frontend.Expr.var "r_1"
                      ]
                  ]
              ]),
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "var_result"
              ] (EvmCompiler.Solidity.Frontend.Expr.var "var")
          ],
        EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "mstore" [
            EvmCompiler.Solidity.Frontend.Expr.var "_1",
            EvmCompiler.Solidity.Frontend.Expr.var "var_result"
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "return" [
            EvmCompiler.Solidity.Frontend.Expr.var "_1",
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 32)
          ])
      ]
  ] [
    ("panic_error_0x11", EvmCompiler.Solidity.Frontend.FunctionDef.mk [] [] [
        EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "mstore" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0),
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "shl" [
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 224),
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1313373041)
              ]
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "mstore" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 4),
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 17)
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "revert" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0),
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 36)
          ])
      ]),
    ("wrapping_div_uint256_389", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "x"
      ] [
        "r"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "_1"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "_1"
          ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "r"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "shr" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1),
            EvmCompiler.Solidity.Frontend.Expr.var "x"
          ])
      ]),
    ("wrapping_div_uint256", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "x"
      ] [
        "r"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "_1"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "_1"
          ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "r"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
            EvmCompiler.Solidity.Frontend.Expr.var "x",
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 6)
          ])
      ]),
    ("wrapping_div_uint256_391", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "x"
      ] [
        "r"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "_1"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "_1"
          ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "r"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
            EvmCompiler.Solidity.Frontend.Expr.var "x",
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 31536000)
          ])
      ]),
    ("checked_mul_uint256", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "x",
        "y"
      ] [
        "product"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "product"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "mul" [
            EvmCompiler.Solidity.Frontend.Expr.var "x",
            EvmCompiler.Solidity.Frontend.Expr.var "y"
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.ifThen (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "iszero" [
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "or" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "iszero" [
                    EvmCompiler.Solidity.Frontend.Expr.var "x"
                  ],
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "eq" [
                    EvmCompiler.Solidity.Frontend.Expr.var "y",
                    EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
                        EvmCompiler.Solidity.Frontend.Expr.var "product",
                        EvmCompiler.Solidity.Frontend.Expr.var "x"
                      ]
                  ]
              ]
          ]) [
            EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "panic_error_0x11" [])
          ]
      ]),
    ("checked_add_uint256_392", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "y"
      ] [
        "sum"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "sum"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "add" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1000000000000000000000000000),
            EvmCompiler.Solidity.Frontend.Expr.var "y"
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.ifThen (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "gt" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1000000000000000000000000000),
            EvmCompiler.Solidity.Frontend.Expr.var "sum"
          ]) [
            EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "panic_error_0x11" [])
          ]
      ]),
    ("checked_add_uint256", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "x",
        "y"
      ] [
        "sum"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "sum"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "add" [
            EvmCompiler.Solidity.Frontend.Expr.var "x",
            EvmCompiler.Solidity.Frontend.Expr.var "y"
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.ifThen (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "gt" [
            EvmCompiler.Solidity.Frontend.Expr.var "x",
            EvmCompiler.Solidity.Frontend.Expr.var "sum"
          ]) [
            EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "panic_error_0x11" [])
          ]
      ]),
    ("fun_calculateCompoundedInterest", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "var_currentTimestamp"
      ] [
        "var_"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "var_"
          ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "diff"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "add" [
            EvmCompiler.Solidity.Frontend.Expr.var "var_currentTimestamp",
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "not" [
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)
              ]
          ])),
        EvmCompiler.Solidity.Frontend.Stmt.ifThen (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "gt" [
            EvmCompiler.Solidity.Frontend.Expr.var "diff",
            EvmCompiler.Solidity.Frontend.Expr.var "var_currentTimestamp"
          ]) [
            EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "panic_error_0x11" [])
          ],
        EvmCompiler.Solidity.Frontend.Stmt.ifThen (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "eq" [
            EvmCompiler.Solidity.Frontend.Expr.var "var_currentTimestamp",
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1)
          ]) [
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "var_"
              ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1000000000000000000000000000)),
            EvmCompiler.Solidity.Frontend.Stmt.leave
          ],
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "expr"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "add" [
            EvmCompiler.Solidity.Frontend.Expr.var "var_currentTimestamp",
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "not" [
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1)
              ]
          ])),
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "expr_1"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.switch (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "gt" [
            EvmCompiler.Solidity.Frontend.Expr.var "diff",
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 2)
          ]) [
            (EvmCompiler.Solidity.Frontend.SwitchCaseValue.word (EvmYul.UInt256.ofNat 0), [
                  EvmCompiler.Solidity.Frontend.Stmt.assign [
                      "expr_1"
                    ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))
                ])
          ] [
            EvmCompiler.Solidity.Frontend.Stmt.assign [
                "expr_1"
              ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "add" [
                EvmCompiler.Solidity.Frontend.Expr.var "var_currentTimestamp",
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "not" [
                    EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 2)
                  ]
              ])
          ],
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "x"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "fun_rayMul" [
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
          ])),
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "r"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "_1"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0))),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "_1"
          ] (EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "r"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
            EvmCompiler.Solidity.Frontend.Expr.var "x",
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 994519296000000)
          ]),
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "r_1"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "fun_rayMul" [
                EvmCompiler.Solidity.Frontend.Expr.var "r",
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000)
              ],
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 31536000)
          ])),
        EvmCompiler.Solidity.Frontend.Stmt.letDecl [
            "expr_2"
          ] (some (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "wrapping_div_uint256_389" [
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                    EvmCompiler.Solidity.Frontend.Expr.var "diff",
                    EvmCompiler.Solidity.Frontend.Expr.var "expr"
                  ],
                EvmCompiler.Solidity.Frontend.Expr.var "r"
              ]
          ])),
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "var_"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_add_uint256" [
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_add_uint256" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_add_uint256_392" [
                    EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "wrapping_div_uint256_391" [
                        EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 50000000000000000000000000),
                            EvmCompiler.Solidity.Frontend.Expr.var "diff"
                          ]
                      ]
                  ],
                EvmCompiler.Solidity.Frontend.Expr.var "expr_2"
              ],
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "wrapping_div_uint256" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                    EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                        EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.user "checked_mul_uint256" [
                            EvmCompiler.Solidity.Frontend.Expr.var "diff",
                            EvmCompiler.Solidity.Frontend.Expr.var "expr"
                          ],
                        EvmCompiler.Solidity.Frontend.Expr.var "expr_1"
                      ],
                    EvmCompiler.Solidity.Frontend.Expr.var "r_1"
                  ]
              ]
          ])
      ]),
    ("fun_rayMul", EvmCompiler.Solidity.Frontend.FunctionDef.mk [
        "var_a",
        "var_b"
      ] [
        "var_c"
      ] [
        EvmCompiler.Solidity.Frontend.Stmt.ifThen (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "iszero" [
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "or" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "iszero" [
                    EvmCompiler.Solidity.Frontend.Expr.var "var_b"
                  ],
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "iszero" [
                    EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "gt" [
                        EvmCompiler.Solidity.Frontend.Expr.var "var_a",
                        EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
                            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "not" [
                                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 500000000000000000000000000)
                              ],
                            EvmCompiler.Solidity.Frontend.Expr.var "var_b"
                          ]
                      ]
                  ]
              ]
          ]) [
            EvmCompiler.Solidity.Frontend.Stmt.exprStmt (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "revert" [
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0),
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 0)
              ])
          ],
        EvmCompiler.Solidity.Frontend.Stmt.assign [
            "var_c"
          ] (EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "div" [
            EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "add" [
                EvmCompiler.Solidity.Frontend.Expr.call EvmCompiler.Solidity.Frontend.CallKind.primitive "mul" [
                    EvmCompiler.Solidity.Frontend.Expr.var "var_a",
                    EvmCompiler.Solidity.Frontend.Expr.var "var_b"
                  ],
                EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 500000000000000000000000000)
              ],
            EvmCompiler.Solidity.Frontend.Expr.lit (EvmYul.UInt256.ofNat 1000000000000000000000000000)
          ])
      ])
  ] [
    EvmCompiler.Solidity.Frontend.DataSection.mk none [
        UInt8.ofNat 162,
        UInt8.ofNat 100,
        UInt8.ofNat 105,
        UInt8.ofNat 112,
        UInt8.ofNat 102,
        UInt8.ofNat 115,
        UInt8.ofNat 88,
        UInt8.ofNat 34,
        UInt8.ofNat 18,
        UInt8.ofNat 32,
        UInt8.ofNat 96,
        UInt8.ofNat 79,
        UInt8.ofNat 168,
        UInt8.ofNat 223,
        UInt8.ofNat 106,
        UInt8.ofNat 214,
        UInt8.ofNat 236,
        UInt8.ofNat 18,
        UInt8.ofNat 16,
        UInt8.ofNat 195,
        UInt8.ofNat 11,
        UInt8.ofNat 1,
        UInt8.ofNat 92,
        UInt8.ofNat 138,
        UInt8.ofNat 29,
        UInt8.ofNat 112,
        UInt8.ofNat 25,
        UInt8.ofNat 10,
        UInt8.ofNat 97,
        UInt8.ofNat 149,
        UInt8.ofNat 70,
        UInt8.ofNat 168,
        UInt8.ofNat 135,
        UInt8.ofNat 173,
        UInt8.ofNat 124,
        UInt8.ofNat 221,
        UInt8.ofNat 175,
        UInt8.ofNat 126,
        UInt8.ofNat 247,
        UInt8.ofNat 19,
        UInt8.ofNat 133,
        UInt8.ofNat 241,
        UInt8.ofNat 100,
        UInt8.ofNat 115,
        UInt8.ofNat 111,
        UInt8.ofNat 108,
        UInt8.ofNat 99,
        UInt8.ofNat 67,
        UInt8.ofNat 0,
        UInt8.ofNat 8,
        UInt8.ofNat 26,
        UInt8.ofNat 0,
        UInt8.ofNat 51
      ]
  ] [] [
    EvmCompiler.Solidity.Frontend.ObjectItemRef.data 0
  ])

def programToYul : Option EvmCompiler.Yul.Program :=
  program.toYulProgram?

noncomputable def programToObjects : Option EvmCompiler.Objects.Program :=
  program.toObjects?

def programUncheckedTarget : Option EvmCompiler.Assembly.TargetProgram :=
  program.compileUnchecked?

def programUncheckedBytecode : Option ByteArray :=
  program.bytecodeUnchecked?

def programUncheckedObjectImage : Option EvmCompiler.Solidity.Frontend.ObjectImage :=
  program.object.bytecodeImageUnchecked?

def programUncheckedBytecodeImage : Option ByteArray :=
  Option.map
    (fun image => EvmCompiler.Assembly.Bytecode.ofList image.bytes)
    programUncheckedObjectImage

noncomputable def programCheckedObjectImage :
    Option EvmCompiler.Solidity.Frontend.ObjectImage :=
  program.object.bytecodeImageChecked?

noncomputable def programCheckedBytecodeImage : Option ByteArray :=
  Option.map
    (fun image => EvmCompiler.Assembly.Bytecode.ofList image.bytes)
    programCheckedObjectImage

def programLinkerSymbols :
    List (EvmCompiler.Solidity.Frontend.Name × EvmCompiler.Solidity.Frontend.Word) :=
  []

def programUncheckedObjectImageWithLinkerSymbols :
    Option EvmCompiler.Solidity.Frontend.ObjectImage :=
  program.object.bytecodeImageUncheckedWithLinkerSymbols?
    programLinkerSymbols

def programUncheckedBytecodeImageWithLinkerSymbols : Option ByteArray :=
  Option.map
    (fun image => EvmCompiler.Assembly.Bytecode.ofList image.bytes)
    programUncheckedObjectImageWithLinkerSymbols

noncomputable def programCheckedObjectImageWithLinkerSymbols :
    Option EvmCompiler.Solidity.Frontend.ObjectImage :=
  program.object.bytecodeImageCheckedWithLinkerSymbols?
    programLinkerSymbols

noncomputable def programCheckedBytecodeImageWithLinkerSymbols :
    Option ByteArray :=
  Option.map
    (fun image => EvmCompiler.Assembly.Bytecode.ofList image.bytes)
    programCheckedObjectImageWithLinkerSymbols

def programResolvedObjectData :
    Option EvmCompiler.Solidity.Frontend.Program :=
  program.resolveObjectBuiltinsWithComputedObjectDataAndLinkerSymbols?
    programLinkerSymbols

def programToYulWithComputedObjectData :
    Option EvmCompiler.Yul.Program :=
  program.toYulProgramWithComputedObjectDataAndLinkerSymbols?
    programLinkerSymbols

noncomputable def programToObjectsWithComputedObjectData :
    Option EvmCompiler.Objects.Program :=
  program.toObjectsWithComputedObjectDataAndLinkerSymbols?
    programLinkerSymbols

noncomputable def programCheckedAssemblyWithComputedObjectData :
    Option EvmCompiler.Assembly.Program :=
  program.compileCheckedWithComputedObjectDataAndLinkerSymbols?
    programLinkerSymbols

noncomputable def programToYulWithComputedObjectDataCheckedAssembly : Option EvmCompiler.Assembly.Program := do
  let yul ← programToYulWithComputedObjectData
  EvmCompiler.Yul.Program.compileSolcChecked? yul

noncomputable def programToYulWithComputedObjectDataTarget : Option EvmCompiler.Assembly.TargetProgram := do
  let asm ← programToYulWithComputedObjectDataCheckedAssembly
  EvmCompiler.Assembly.compile? asm

noncomputable def programToYulWithComputedObjectDataBytecode : Option ByteArray := do
  let target ← programToYulWithComputedObjectDataTarget
  some (EvmCompiler.Assembly.Bytecode.encodeTarget target)

noncomputable def programToYulCheckedAssembly : Option EvmCompiler.Assembly.Program := do
  let yul ← programToYul
  EvmCompiler.Yul.Program.compileSolcChecked? yul

noncomputable def programToYulTarget : Option EvmCompiler.Assembly.TargetProgram := do
  let asm ← programToYulCheckedAssembly
  EvmCompiler.Assembly.compile? asm

noncomputable def programToYulBytecode : Option ByteArray := do
  let target ← programToYulTarget
  some (EvmCompiler.Assembly.Bytecode.encodeTarget target)

def objectLayout : EvmCompiler.Solidity.Frontend.ObjectLayout :=
  EvmCompiler.Solidity.Frontend.ObjectLayout.mk []

def programToYulWithLayout : Option EvmCompiler.Yul.Program :=
  program.toYulProgramWithLayout? objectLayout

noncomputable def programToObjectsWithLayout :
    Option EvmCompiler.Objects.Program :=
  program.toObjectsWithLayout? objectLayout

def programUncheckedTargetWithLayout : Option EvmCompiler.Assembly.TargetProgram :=
  program.compileUncheckedWithLayout? objectLayout

def programUncheckedBytecodeWithLayout : Option ByteArray :=
  program.bytecodeUncheckedWithLayout? objectLayout

noncomputable def programToYulWithLayoutCheckedAssembly : Option EvmCompiler.Assembly.Program := do
  let yul ← programToYulWithLayout
  EvmCompiler.Yul.Program.compileSolcChecked? yul

noncomputable def programToYulWithLayoutTarget : Option EvmCompiler.Assembly.TargetProgram := do
  let asm ← programToYulWithLayoutCheckedAssembly
  EvmCompiler.Assembly.compile? asm

noncomputable def programToYulWithLayoutBytecode : Option ByteArray := do
  let target ← programToYulWithLayoutTarget
  some (EvmCompiler.Assembly.Bytecode.encodeTarget target)

open EvmCompiler.Functions.CallAwareSpill

def dbgRange : ScratchRange := plannedScratchRange 64

#eval
  match programToObjects with
  | none => "objects none"
  | some objects =>
      let lower := objects.root.code
      match EvmCompiler.Functions.FunList.find? "wrapping_div_uint256" lower.functions with
      | none => "fn none"
      | some fn =>
          if compileFunDefWithSwitchFallback? dbgRange lower fn |>.isSome then
            "fun some"
          else
            "fun none"

#eval
  match programToObjects with
  | none => "objects none"
  | some objects =>
      let lower := objects.root.code
      match EvmCompiler.Functions.FunList.find? "wrapping_div_uint256" lower.functions with
      | none => "fn none"
      | some fn =>
          let entryStack := fn.params.reverse
          match
              compileLocalsBlockSpan? dbgRange fn.params entryStack
                (layoutOfParamStack fn.params)
                { stmts := initReturnsInSourceScopeOrder fn.returns } with
          | none => "init none"
          | some init =>
              match
                  compileBlockOpenWithSwitchFallback? dbgRange lower fn.returns
                    init.sourceScope init.stackLayout init.layout fn.body with
              | none => "body none"
              | some body =>
                  match
                      appendReturnFallthrough? dbgRange fn.returns
                        { sourceScope := body.sourceScope
                          stackLayout := body.stackLayout
                          layout := body.layout
                          block := ExpressionsBlock.append init.block body.block } with
                  | none => "return none"
                  | some _ => "return some"
