import EvmCompiler.Assembly.InteractionBytecode
import EvmCompiler.Structured.InteractionControlPreservation
import EvmCompiler.TypedCfg.InteractionPreservation

#check EvmCompiler.Simulation.OpenWorld
#check EvmCompiler.Simulation.OpenWorld.installYulShared
#check EvmCompiler.Simulation.OpenWorld.installEVMShared
#check EvmCompiler.Simulation.Interaction.bind
#check EvmCompiler.Simulation.Interaction.Rel.refl
#check EvmCompiler.Simulation.Interaction.Rel.symm
#check EvmCompiler.Simulation.Interaction.Rel.trans
#check EvmCompiler.Simulation.Interaction.Rel.bind
#check EvmCompiler.Simulation.Interaction.Rel.request_left
#check EvmCompiler.Simulation.Interaction.Rel.interpret
#check EvmCompiler.Simulation.Interaction.Rel.executes
#check EvmCompiler.Assembly.InteractionSemantics.PrimOp.openStep
#check EvmCompiler.Assembly.InteractionSemantics.Source.prim_openStep_rel
#check EvmCompiler.Assembly.InteractionSemantics.Target.openRunNResult
#check EvmCompiler.Assembly.InteractionPreservation.stepAt_emit_open_rel
#check EvmCompiler.Assembly.InteractionPreservation.stepAt_emit_open_result_rel
#check EvmCompiler.Assembly.InteractionPreservation.source_openRunNResult_rel_compiled
#check EvmCompiler.Assembly.InteractionPreservation.source_openRunUntilTransfer_rel_compiled
#check EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_block_rel
#check EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_target_executes
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.call_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.callcode_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.delegatecall_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.staticcall_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.create_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.create2_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Block.lowerBodyFrom?_source_openRunNResult
#check EvmCompiler.TypedCfg.InteractionPreservation.Terminator.lowerAt?_openRunUntilTransfer_rel_of_direct
#check EvmCompiler.TypedCfg.InteractionPreservation.Program.lower?_openRunN_rel
#check EvmCompiler.TypedCfg.InteractionPreservation.Program.compileCertified?_entry_openRunN_rel
#check EvmCompiler.Structured.InteractionPreservation.BasicInstr.openRunAt_toCfg
#check EvmCompiler.Structured.InteractionPreservation.Code.openRun_toCfg
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNWithStop_one
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add_eq_of_allStopped
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.target_allStopped
#check EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_nil_of_compileStmtListFuel?
#check EvmCompiler.Assembly.TargetInstr.ofDecoded?_op_arg
#check EvmCompiler.Assembly.Bytecode.InteractionSemantics.openRunNResult
#check EvmCompiler.Assembly.Bytecode.target_openRunNResult_executes
#check EvmCompiler.Assembly.Bytecode.compile_openRunNResult_executes

#print axioms EvmCompiler.Simulation.OpenAccount.ofYul_toYul
#print axioms EvmCompiler.Simulation.OpenAccount.ofEVM_toEVM
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_call
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_callcode
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_delegatecall
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_staticcall
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_create
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_create2
#print axioms EvmCompiler.Simulation.Interaction.Rel.bind
#print axioms EvmCompiler.Simulation.Interaction.Rel.trans
#print axioms EvmCompiler.Simulation.Interaction.Rel.interpret
#print axioms EvmCompiler.Simulation.Interaction.Rel.executes
#print axioms EvmCompiler.Assembly.InteractionSemantics.Source.prim_openStep_rel
#print axioms EvmCompiler.Assembly.InteractionPreservation.stepAt_emit_open_result_rel
#print axioms EvmCompiler.Assembly.InteractionPreservation.source_openRunUntilTransfer_rel_compiled
#print axioms EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_block_rel
#print axioms EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_target_executes
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Instr.openRunAt_atLoweredEnd
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Block.lowerBodyFrom?_source_openRunNResult
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Terminator.lowerAt?_openRunUntilTransfer_rel_of_direct
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Program.lower?_openRunN_rel
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Program.compileCertified?_entry_openRunN_rel
#print axioms EvmCompiler.Structured.InteractionPreservation.BasicInstr.openRunAt_toCfg
#print axioms EvmCompiler.Structured.InteractionPreservation.Code.openRun_toCfg
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNWithStop_one
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add_eq_of_allStopped
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.target_allStopped
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_nil_of_compileStmtListFuel?
#print axioms EvmCompiler.Assembly.Bytecode.target_openRunNResult_executes
#print axioms EvmCompiler.Assembly.Bytecode.compile_openRunNResult_executes
