import EvmCompiler.Assembly.InteractionBytecode
import EvmCompiler.Structured.InteractionControlPreservation
import EvmCompiler.Structured.InteractionLeafPreservation
import EvmCompiler.Structured.InteractionBranchPreservation
import EvmCompiler.Structured.InteractionSwitchPreservation
import EvmCompiler.Structured.InteractionLoopPreservation
import EvmCompiler.Structured.InteractionCallPreservation
import EvmCompiler.Structured.InteractionOwnerPreservation
import EvmCompiler.Expressions.InteractionPreservation
import EvmCompiler.Functions.AllocationInteractionSelectedCallEntry
import EvmCompiler.Functions.AllocationInteractionFrameExecution
import EvmCompiler.Functions.AllocationInteractionFramePreservation
import EvmCompiler.Functions.AllocationInteractionPrimitiveResource
import EvmCompiler.Functions.AllocationInteractionPreparedCallResources
import EvmCompiler.Functions.AllocationInteractionCallTargets
import EvmCompiler.Functions.AllocationInteractionRecursiveResource
import EvmCompiler.Functions.AllocationInteractionCallResultResource
import EvmCompiler.Functions.AllocationInteractionCallStatementResource
import EvmCompiler.Locals.InteractionPreservation
import EvmCompiler.TypedCfg.InteractionPreservation

#check EvmCompiler.Simulation.OpenWorld
#check EvmCompiler.Functions.AllocationInteractionCall.CallTargets.forward
#check EvmCompiler.Functions.AllocationInteractionCall.CallTargets.forward_bounded
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.combine
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.expr
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.assign
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.let_
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.brk
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.cont
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.block
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.if_
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.switch
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.leave
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.terminal
#check EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.terminalArgs
#check EvmCompiler.Simulation.OpenWorld.installYulShared
#check EvmCompiler.Simulation.OpenWorld.installEVMShared
#check EvmCompiler.Simulation.Interaction.bind
#check EvmCompiler.Simulation.Interaction.Rel.refl
#check EvmCompiler.Simulation.Interaction.Rel.symm
#check EvmCompiler.Simulation.Interaction.Rel.trans
#check EvmCompiler.Simulation.Interaction.Rel.bind
#check EvmCompiler.Simulation.Interaction.Rel.request_left
#check EvmCompiler.Simulation.Interaction.Rel.interpret
#check EvmCompiler.Simulation.Interaction.Rel.executes
#check EvmCompiler.Assembly.InteractionSemantics.PrimOp.openStep
#check EvmCompiler.Assembly.InteractionSemantics.Source.prim_openStep_rel
#check EvmCompiler.Assembly.InteractionSemantics.Target.openRunNResult
#check EvmCompiler.Assembly.InteractionPreservation.stepAt_emit_open_rel
#check EvmCompiler.Assembly.InteractionPreservation.stepAt_emit_open_result_rel
#check EvmCompiler.Assembly.InteractionPreservation.source_openRunNResult_rel_compiled
#check EvmCompiler.Assembly.InteractionPreservation.source_openRunUntilTransfer_rel_compiled
#check EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_block_rel
#check EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_target_executes
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.call_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.callcode_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.delegatecall_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.staticcall_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.create_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Instr.create2_lowerAt_openRunNResult_eq
#check EvmCompiler.TypedCfg.InteractionPreservation.Block.lowerBodyFrom?_source_openRunNResult
#check EvmCompiler.TypedCfg.InteractionPreservation.Terminator.lowerAt?_openRunUntilTransfer_rel_of_direct
#check EvmCompiler.TypedCfg.InteractionPreservation.Program.lower?_openRunN_rel
#check EvmCompiler.TypedCfg.InteractionPreservation.Program.compileCertified?_entry_openRunN_rel
#check EvmCompiler.Structured.InteractionPreservation.BasicInstr.openRunAt_toCfg
#check EvmCompiler.Structured.InteractionPreservation.Code.openRun_toCfg
#check EvmCompiler.Structured.InteractionPrimitivePreservation.BasicOp.openStepEVM_append_stack_rel
#check EvmCompiler.Expressions.InteractionPreservation.Expr.openRun_compile
#check EvmCompiler.Expressions.InteractionPreservation.ExprSeq.openRun_compile
#check EvmCompiler.Expressions.InteractionPreservation.Block.openRun_toStructured
#check EvmCompiler.Expressions.InteractionPreservation.Stmt.openRun_toStructured
#check EvmCompiler.Expressions.InteractionPreservation.Stmt.openRunForLoop_toStructured
#check EvmCompiler.Expressions.InteractionPreservation.Program.openRunState_toStructured
#check EvmCompiler.Expressions.InteractionPreservation.Program.openRun_toStructured
#check EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_call
#check EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_callcode
#check EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_delegatecall
#check EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_staticcall
#check EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_create
#check EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_create2
#check EvmCompiler.Locals.InteractionPreservation.Primitive.openEval_op
#check EvmCompiler.Locals.InteractionPreservation.Expr.openEval_compileCode
#check EvmCompiler.Locals.InteractionPreservation.Expr.openEvalSeq_compileCode
#check EvmCompiler.Structured.TypedCfgPreservation.ActivationFrameMatches
#check EvmCompiler.Structured.TypedCfgPreservation.ActivationFrameMatches.of_stateRel
#check EvmCompiler.Structured.InteractionSemantics.Code.openRun_returns
#check EvmCompiler.Structured.TypedCfgCompilerFacts.LabelBeforeSupply
#check EvmCompiler.Structured.TypedCfgCompilerFacts.ContinuationLabelsBeforeSupply
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNWithStop_one
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithRefinedStop_add
#check EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add_eq_map_addFuel_of_allStopped
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.target_allStopped
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesUnder.exec
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.Rel.regular_elim_of_required_fallthrough
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.close_refined
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.splice_refined_jump
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.prepend_step_jump
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.prepend_closed_jump
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.sequence
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.ignore_tail_of_no_fallthrough
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.sequence
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.ignore_tail_of_no_fallthrough
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.pad_stop
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.change_result_of_required_fallthrough
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.prepend_closed_jump
#check EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.of_openStep
#check EvmCompiler.Structured.InteractionControlPreservation.Stmt.openStep_code_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_within_stop_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_within_resume_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_nil_of_compileStmtListFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_nil_exec_under_of_compileStmtListFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_cons_exec_under_of_compileStmtListFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_cons_within_of_compileStmtListFuel?
#check EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_code_cons_within_of_compileStmtListFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openStep_brk_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_brk_within_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openStep_cont_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_cont_within_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openStep_leave_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_leave_within_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openStep_terminal_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_terminal_within_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionBranchPreservation.Condition.openRunCondition_jumpi_toCfg
#check EvmCompiler.Structured.InteractionBranchPreservation.Code.openRun_jump_toCfg
#check EvmCompiler.Structured.InteractionBranchPreservation.Condition.openStep_if_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionBranchPreservation.Stmt.openRun_if_exec_under_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionBranchPreservation.Stmt.openRun_if_within_stop_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openStep_test
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openStep_pop_jump
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_default_none_of_compileDefaultFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_default_some_of_compileDefaultFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_cases_some_of_compileCasesFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_cases_none_of_compileCasesFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_default_some_exec_under_of_compileDefaultFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_cases_some_exec_under_of_compileCasesFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Stmt.openRun_switch_exec_under_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionSwitchPreservation.Stmt.openRun_switch_within_stop_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionLoopPreservation.Loop.openRunForLoop_exec_under
#check EvmCompiler.Structured.InteractionLoopPreservation.Loop.Stmt.openRun_for_exec_under_of_compileStmtFuel?
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.FragmentContract
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.StmtContract
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.BlockOwnerAt
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.code_exec
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.if_exec
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.call_exec
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.exec_succ
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.block_owner
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.GeneratedProgram.main_exec
#check EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_exec
#check EvmCompiler.Assembly.TargetInstr.ofDecoded?_op_arg
#check EvmCompiler.Assembly.Bytecode.InteractionSemantics.openRunNResult
#check EvmCompiler.Assembly.Bytecode.target_openRunNResult_executes
#check EvmCompiler.Assembly.Bytecode.compile_openRunNResult_executes

#print axioms EvmCompiler.Simulation.OpenAccount.ofYul_toYul
#print axioms EvmCompiler.Simulation.OpenAccount.ofEVM_toEVM
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_call
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_callcode
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_delegatecall
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_staticcall
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_create
#print axioms EvmCompiler.Simulation.ExternalKind.classifies_create2
#print axioms EvmCompiler.Simulation.Interaction.Rel.bind
#print axioms EvmCompiler.Simulation.Interaction.Rel.trans
#print axioms EvmCompiler.Simulation.Interaction.Rel.interpret
#print axioms EvmCompiler.Simulation.Interaction.Rel.executes
#print axioms EvmCompiler.Assembly.InteractionSemantics.Source.prim_openStep_rel
#print axioms EvmCompiler.Assembly.InteractionPreservation.stepAt_emit_open_result_rel
#print axioms EvmCompiler.Assembly.InteractionPreservation.source_openRunUntilTransfer_rel_compiled
#print axioms EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_block_rel
#print axioms EvmCompiler.Assembly.InteractionPreservation.compile_openRunNResult_target_executes
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Instr.openRunAt_atLoweredEnd
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Block.lowerBodyFrom?_source_openRunNResult
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Terminator.lowerAt?_openRunUntilTransfer_rel_of_direct
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Program.lower?_openRunN_rel
#print axioms EvmCompiler.TypedCfg.InteractionPreservation.Program.compileCertified?_entry_openRunN_rel
#print axioms EvmCompiler.Structured.InteractionPreservation.BasicInstr.openRunAt_toCfg
#print axioms EvmCompiler.Structured.InteractionPreservation.Code.openRun_toCfg
#print axioms EvmCompiler.Structured.InteractionPrimitivePreservation.BasicOp.openStepEVM_append_stack_rel
#print axioms EvmCompiler.Expressions.InteractionPreservation.Expr.openRun_compile
#print axioms EvmCompiler.Expressions.InteractionPreservation.ExprSeq.openRun_compile
#print axioms EvmCompiler.Expressions.InteractionPreservation.Block.openRun_toStructured
#print axioms EvmCompiler.Expressions.InteractionPreservation.Stmt.openRun_toStructured
#print axioms EvmCompiler.Expressions.InteractionPreservation.Stmt.openRunForLoop_toStructured
#print axioms EvmCompiler.Expressions.InteractionPreservation.Program.openRunState_toStructured
#print axioms EvmCompiler.Expressions.InteractionPreservation.Program.openRun_toStructured
#print axioms EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_call
#print axioms EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_callcode
#print axioms EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_delegatecall
#print axioms EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_staticcall
#print axioms EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_create
#print axioms EvmCompiler.Locals.InteractionSemantics.Primitive.openEval_create2
#print axioms EvmCompiler.Locals.InteractionPreservation.Primitive.openEval_op
#print axioms EvmCompiler.Locals.InteractionPreservation.Expr.openEval_compileCode
#print axioms EvmCompiler.Locals.InteractionPreservation.Expr.openEvalSeq_compileCode
#print axioms EvmCompiler.Structured.TypedCfgPreservation.ActivationFrameMatches.of_stateRel
#print axioms EvmCompiler.Structured.InteractionSemantics.Code.openRun_returns
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNWithStop_one
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithRefinedStop_add
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Program.openRunNResultWithStop_add_eq_map_addFuel_of_allStopped
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.target_allStopped
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesUnder.exec
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.prepend_closed_jump
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.sequence
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.ExecPreservesUnder.ignore_tail_of_no_fallthrough
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.sequence
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.ignore_tail_of_no_fallthrough
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.pad_stop
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.change_result_of_required_fallthrough
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.prepend_closed_jump
#print axioms EvmCompiler.Structured.InteractionControlPreservation.OpenOutcome.PreservesWithin.of_openStep
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Stmt.openStep_code_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_within_stop_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_within_resume_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Stmt.openRun_code_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_nil_of_compileStmtListFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_nil_exec_under_of_compileStmtListFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_cons_exec_under_of_compileStmtListFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_cons_within_of_compileStmtListFuel?
#print axioms EvmCompiler.Structured.InteractionControlPreservation.Block.openRun_code_cons_within_of_compileStmtListFuel?
#print axioms EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_brk_within_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_cont_within_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_leave_within_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionLeafPreservation.Stmt.openRun_terminal_within_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionBranchPreservation.Condition.openRunCondition_jumpi_toCfg
#print axioms EvmCompiler.Structured.InteractionBranchPreservation.Code.openRun_jump_toCfg
#print axioms EvmCompiler.Structured.InteractionBranchPreservation.Condition.openStep_if_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionBranchPreservation.Stmt.openRun_if_exec_under_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionBranchPreservation.Stmt.openRun_if_within_stop_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openStep_test
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openStep_pop_jump
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_cases_some_of_compileCasesFuel?
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_cases_none_of_compileCasesFuel?
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_default_some_exec_under_of_compileDefaultFuel?
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Switch.openRun_cases_some_exec_under_of_compileCasesFuel?
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Stmt.openRun_switch_exec_under_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionSwitchPreservation.Stmt.openRun_switch_within_stop_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionLoopPreservation.Loop.openRunForLoop_exec_under
#print axioms EvmCompiler.Structured.InteractionLoopPreservation.Loop.Stmt.openRun_for_exec_under_of_compileStmtFuel?
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Instr.openRunAt_eq_done_of_not_prim
#print axioms EvmCompiler.TypedCfg.InteractionSemantics.Block.openRunBody_eq_done_of_forall_not_prim
#print axioms EvmCompiler.Structured.InteractionCallPreservation.Call.openStep_entry_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionCallPreservation.Call.openRunNResult_procEntry
#print axioms EvmCompiler.Structured.InteractionCallPreservation.Call.openStep_dispatch
#print axioms EvmCompiler.Structured.InteractionCallPreservation.Call.openRun_call_exec_under
#print axioms EvmCompiler.Structured.InteractionCallPreservation.Call.openRun_call_exec_under_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.code_exec
#print axioms EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.if_exec
#print axioms EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.call_exec
#print axioms EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.Stmt.exec_succ
#print axioms EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.block_owner
#print axioms EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.GeneratedProgram.main_exec
#print axioms EvmCompiler.Structured.InteractionOwnerPreservation.OpenOutcome.GeneratedProgram.generateWithProcEntryShapes?_main_exec
#print axioms EvmCompiler.Assembly.Bytecode.target_openRunNResult_executes
#print axioms EvmCompiler.Assembly.Bytecode.compile_openRunNResult_executes
#print axioms EvmCompiler.Functions.AllocationInteractionCall.ArgList.forwardArg
#print axioms EvmCompiler.Functions.AllocationInteractionCall.ArgList.forward
#print axioms EvmCompiler.Functions.AllocationInteractionCall.CalleeEntry.stack_of_arguments
#print axioms EvmCompiler.Functions.AllocationInteractionCall.CalleeEntry.splitArgs_of_arguments
#print axioms EvmCompiler.Functions.AllocationInteractionCall.SelectedCallee.Prepared.stack_entry_of_arguments
#print axioms EvmCompiler.Functions.AllocationInteractionCall.CoreCursor.callComponents
#print axioms EvmCompiler.Functions.AllocationInteractionFrameExecution.allocatorAdvance_openRun
#print axioms EvmCompiler.Functions.AllocationInteractionFrame.AllocatorEffect.of_memory_eq_active_growth
#print axioms EvmCompiler.Functions.AllocationInteractionFrame.BoundedEffect.of_machine_eq
#print axioms EvmCompiler.Functions.AllocationInteractionFrameExecution.framePrealloc_openRun
#print axioms EvmCompiler.Functions.AllocationInteractionFrameExecution.scratchFrameAcquire_openRun
#print axioms EvmCompiler.Functions.AllocationInteractionFramePreservation.allocatorAdvanceTarget_machineRel
#print axioms EvmCompiler.Functions.AllocationInteractionFramePreservation.framePreallocTarget_machineRel
#print axioms EvmCompiler.Functions.AllocationInteractionFramePreservation.scratchFrameAcquire_correct
#print axioms EvmCompiler.Functions.AllocationInteractionCall.CalleeEntry.scratch_of_arguments
#print axioms EvmCompiler.Functions.AllocationInteractionCall.SelectedCallee.Prepared.scratch_entry_of_arguments
#print axioms EvmCompiler.Functions.AllocationInteractionExpressionResource.forwardExpr
#print axioms EvmCompiler.Functions.AllocationInteractionCallArgumentResources.forward
#print axioms EvmCompiler.Functions.AllocationInteractionPrimitiveResource.canonicalPrimitiveForward
#print axioms EvmCompiler.Functions.AllocationInteractionFramePreservation.scratchFrameAcquire_activation_correct
#print axioms EvmCompiler.Functions.AllocationInteractionFramePreservation.scratchFrameRelease_activation_correct
#print axioms EvmCompiler.Functions.AllocationInteractionCall.PreparedArguments.scratch
#print axioms EvmCompiler.Functions.AllocationInteractionRelation.ActivationStateRel.assign_stack_live_at
#print axioms EvmCompiler.Functions.AllocationInteractionFrame.BoundedEffect.of_mstore_above
#print axioms EvmCompiler.Functions.AllocationInteractionCall.CallTargets.forward
#print axioms EvmCompiler.Functions.AllocationInteractionCall.CallTargets.forward_bounded
#print axioms EvmCompiler.Simulation.Interaction.Rel.inter
#print axioms EvmCompiler.Functions.AllocationInteractionResourceComposition.cons
#print axioms EvmCompiler.Functions.AllocationInteractionStatementResource.expr_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.expr
#print axioms EvmCompiler.Functions.AllocationInteractionFrame.ActivationOwned.boundedEffect_of_scratchStore
#print axioms EvmCompiler.Functions.AllocationInteractionStatementResource.assign_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.assign
#print axioms EvmCompiler.Functions.AllocationInteractionFrame.ActivationOwned.boundedEffect_of_scratchStoreSlot
#print axioms EvmCompiler.Functions.AllocationInteractionStatementResource.stack_let_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionStatementResource.scratch_let_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.let_
#print axioms EvmCompiler.Functions.AllocationInteractionCleanupResource.Plain.forward_allocator
#print axioms EvmCompiler.Functions.AllocationInteractionAbruptResource.brk_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionAbruptResource.cont_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.brk
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.cont
#print axioms EvmCompiler.Functions.AllocationInteractionControlResource.block_of_components
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.block
#print axioms EvmCompiler.Functions.AllocationInteractionExpressionResource.forwardOne
#print axioms EvmCompiler.Functions.AllocationInteractionExpressionResource.forwardCondition
#print axioms EvmCompiler.Functions.AllocationInteractionControlResource.if_of_components
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.if_
#print axioms EvmCompiler.Functions.AllocationInteractionControlResource.switch_of_components
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.switch
#print axioms EvmCompiler.Functions.AllocationInteractionCleanupResource.Preserving.forward_zero_allocator
#print axioms EvmCompiler.Functions.AllocationInteractionLeaveResource.leave_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.leave
#print axioms EvmCompiler.Functions.AllocationInteractionTerminalResource.Invocation.forward_shared_allocator
#print axioms EvmCompiler.Functions.AllocationInteractionTerminalResource.terminal_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.terminal
#print axioms EvmCompiler.Functions.AllocationInteractionTerminalResource.terminalArgs_of_lower_compile
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.CursorRuntimeAt.terminalArgs
#print axioms EvmCompiler.Functions.AllocationInteractionFrame.OutcomeEffect.prepend_activation
#print axioms EvmCompiler.Functions.AllocationInteractionFrame.Budget.mono
#print axioms EvmCompiler.Functions.AllocationInteractionLoop.forward_effect
#print axioms EvmCompiler.Functions.AllocationInteractionFor.forward_effect
#print axioms EvmCompiler.Functions.AllocationSupport.planRecipeCore?_find?_of_lookupFun?
#print axioms EvmCompiler.Functions.AllocationInteractionCall.CallComponents.selectedCallee
#print axioms EvmCompiler.Functions.AllocationInteractionRecursiveResource.RecursiveOpenRuntime.at_targetFuel
#print axioms EvmCompiler.Functions.AllocationInteractionCallResultResource.SelectedCallee.complete_call
#print axioms EvmCompiler.Functions.AllocationInteractionCall.PreparedArguments.caller_state_of_scratch_result
#print axioms EvmCompiler.Functions.AllocationInteractionCallStatementResource.CallResultRel.returned_with_release
#print axioms EvmCompiler.Functions.AllocationInteractionCallStatementResource.SelectedCallee.stack_after_arguments
#print axioms EvmCompiler.Functions.AllocationInteractionCallStatementResource.SelectedCallee.scratch_after_arguments
