import EvmCompiler.Functions.ObserverSemantics
import EvmCompiler.Functions.AllocationObserverPreservation
import EvmCompiler.Functions.AllocationObserverSafety
import EvmCompiler.Functions.AllocationObserverContext
import EvmCompiler.Functions.AllocationObserverCleanup
import EvmCompiler.Functions.AllocationObserverExpression
import EvmCompiler.Functions.AllocationObserverPrimitive
import EvmCompiler.Functions.AllocationObserverStatement
import EvmCompiler.Expressions.ObserverPreservation
import EvmCompiler.Locals.ObserverSemantics
import EvmCompiler.Public.Observer
import EvmCompiler.Simulation.ObserverPass
import EvmCompiler.Structured.ObserverCallAdequacy
import EvmCompiler.Structured.ObserverFrameInvariant
import EvmCompiler.Structured.ObserverGeneratedAdequacy
import EvmCompiler.Structured.ObserverProgramAdequacy
import EvmCompiler.Structured.ObserverSequenceAdequacy
import EvmCompiler.Yul.FunctionsObserverPreservation
import EvmCompiler.Yul.ObserverSemantics
import EvmCompiler.Yul.StateRelation
import EvmCompiler.Yul.EndToEnd
import EvmCompiler.TypedCfg.ObserverPreservation

#check EvmCompiler.Yul.Source.Effectful.StateModel
#check EvmCompiler.Yul.Source.Effectful.PrimitiveSemantics
#check EvmCompiler.Simulation.ResourceReplay.State
#check EvmCompiler.Locals.ObserverSemantics.Program.ExactReplay
#check EvmCompiler.Functions.Source.Effectful.Program.runState
#check EvmCompiler.Functions.ObserverSemantics.Program.runState
#check EvmCompiler.Functions.ObserverSemantics.stmt_run_let_gas_cons
#check EvmCompiler.Functions.ObserverSemantics.runBody_let_gas_cons
#check EvmCompiler.Functions.ObserverSemantics.stmt_run_call_let_gas_cons
#check EvmCompiler.Functions.AllocationObserverRelation.StateRel
#check EvmCompiler.Functions.AllocationObserverRelation.ScratchStateRel
#check EvmCompiler.Functions.AllocationObserverRelation.ExprResultRel
#check EvmCompiler.Functions.AllocationObserverRelation.ScratchExprResultRel
#check EvmCompiler.Functions.AllocationObserverRelation.Frame.FuelSafe
#check EvmCompiler.Functions.AllocationObserverSafety.PrimitiveMemorySafe
#check EvmCompiler.Functions.AllocationObserverSafety.TerminalMemorySafe
#check EvmCompiler.Functions.AllocationObserverSafety.Expr.MemorySafeEval.eval_eq
#check EvmCompiler.Functions.AllocationObserverSafety.ExprSeq.MemorySafeEval.eval_eq
#check EvmCompiler.Functions.AllocationObserverContext.ExprContext
#check EvmCompiler.Functions.AllocationObserverContext.classify_var
#check EvmCompiler.Functions.AllocationObserverExpression.PrimitiveForward.gas
#check EvmCompiler.Functions.AllocationObserverExpression.PrimitiveForward.msize
#check EvmCompiler.Functions.AllocationObserverPrimitive.SharedFamily.simulate
#check EvmCompiler.Functions.AllocationObserverPrimitive.SharedFamily.primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mload_simulate
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mload_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mstore_simulate
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mstore_primitiveForward
#check EvmCompiler.Compiler.MemoryRelation.OutsideReservation.write_self_both
#check EvmCompiler.Compiler.MemoryRelation.MachineRel.mcopy_both
#check EvmCompiler.Compiler.MemoryRelation.MachineRel.readRange_both
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.copy_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.read_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.keccak256_simulate
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.keccak256_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.logOp_both
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.LogFamily.simulate
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.LogFamily.primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.log0_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.log4_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.canonicalPrimitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.calldatacopy_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.codecopy_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.returndatacopy_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.extcodecopy_primitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mcopy_primitiveForward
#check EvmCompiler.Locals.Source.PrimitiveSemantics.structured_eval_step_exists
#check EvmCompiler.Locals.Source.PrimitiveSemantics.structured_eval_length
#check EvmCompiler.Functions.AllocationObserverExpression.forwardExpr
#check EvmCompiler.Functions.AllocationObserverExpression.forwardExprSeq
#check EvmCompiler.Functions.AllocationObserverExpression.Expr.backward_of_safeEval
#check EvmCompiler.Functions.AllocationObserverExpression.ExprSeq.backward_of_safeEval
#check EvmCompiler.Functions.AllocationObserverExpression.StackPrimitiveForward
#check EvmCompiler.Functions.AllocationObserverExpression.ActivationPrimitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.canonicalStackPrimitiveForward
#check EvmCompiler.Functions.AllocationObserverPrimitive.canonicalActivationPrimitiveForward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_backward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_backward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_backward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_backward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_backward
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_forward_of_compileCode
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_backward_of_compileCode
#check EvmCompiler.Functions.AllocationLowering.scratchStoreExpr_compileCode
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchAssignTop_forward_live
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchAssignTop_backward_live
#check EvmCompiler.Functions.AllocationObserverExpression.Expr.invariant_zero
#check EvmCompiler.Functions.AllocationObserverExpression.Expr.condition_forward
#check EvmCompiler.Functions.AllocationObserverStatement.ExprLeaf.forward_of_invariant
#check EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.forward_of_invariant
#check EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.forward_of_invariant
#check EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtInvariantForward
#check EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularBlockInvariantForward
#check EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtInvariantForward.if_false_of_components
#check EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtInvariantForward.if_true_of_components
#check EvmCompiler.Functions.AllocationLowering.lowerBlockOpen_cons_components
#check EvmCompiler.Locals.Block.compileOpen_append_components
#check EvmCompiler.Functions.AllocationObserverPreservation.Frame.allocatorInit_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameAcquire_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameAcquire_backward
#check EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameRelease_forward
#check EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameRelease_backward
#check EvmCompiler.Structured.EffectSemantics.Code.run_append
#check EvmCompiler.Structured.ObserverSemantics.Code.run_append
#check EvmCompiler.Functions.AllocationObserverRelation.Frame.mstore_end_le_activeBytes
#check EvmCompiler.Functions.AllocationObserverRelation.Frame.noWrap_of_budget_of_scratchFrameConfig?
#check EvmCompiler.Compiler.MemoryRelation.byteAt_writeWord_of_outside
#check EvmCompiler.Compiler.MemoryRelation.MachineRel.mstore_target
#check EvmCompiler.Functions.AllocationObserverRelation.Frame.hostAddressable_of_budget_of_scratchFrameConfig?
#check EvmCompiler.Functions.AllocationObserverPreservation.ObserverCode.run_mstore
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_forward_scratch
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_backward_scratch
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_forward_scratch
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_backward_scratch
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_forward_result
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_backward_result
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_forward_result
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_backward_result
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_forward_result
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_backward_result
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_forward_result_scratch
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_backward_result_scratch
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_forward_result_scratch
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_backward_result_scratch
#check EvmCompiler.Functions.AllocationObserverRelation.ScratchStateRel.declare_stack_live
#check EvmCompiler.Functions.AllocationObserverContext.classify_let_transition
#check EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.compiler_shape
#check EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.forward_of_compilers
#check EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.backward_of_compilers
#check EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.compiler_shape
#check EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.forward_of_compilers
#check EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.backward_of_compilers
#check EvmCompiler.Functions.AllocationObserverCleanup.Plain.forward
#check EvmCompiler.Functions.AllocationObserverCleanup.Plain.backward
#check EvmCompiler.Functions.AllocationObserverCleanup.BreakLeaf.forward_of_compilers
#check EvmCompiler.Functions.AllocationObserverCleanup.BreakLeaf.backward_of_compilers
#check EvmCompiler.Functions.AllocationObserverCleanup.ContinueLeaf.forward_of_compilers
#check EvmCompiler.Functions.AllocationObserverCleanup.ContinueLeaf.backward_of_compilers
#check EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel
#check EvmCompiler.Functions.AllocationObserverRelation.ActivationExprResultRel
#check EvmCompiler.Functions.AllocationObserverRelation.ActivationOutcomeRel
#check EvmCompiler.Functions.AllocationObserverRelation.StoreRel.rebase_prefix_stack_only
#check EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.activeNoWrap
#check EvmCompiler.Functions.AllocationObserverRelation.StateRel.assign_stack_live
#check EvmCompiler.Functions.AllocationObserverRelation.ScratchStateRel.assign_stack_live
#check EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.assign_stack_live
#check EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.assign_scratch
#check EvmCompiler.Functions.AllocationObserverContext.StackExprContext
#check EvmCompiler.Functions.AllocationObserverContext.ActivationExprContext
#check EvmCompiler.Functions.AllocationObserverContext.classify_activation_var
#check EvmCompiler.Functions.AllocationObserverContext.ExprContext.stack_depth_lt_frame
#check EvmCompiler.Functions.AllocationObserverPreservation.ObserverCode.run_swap_pop
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_forward_result_activation
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_forward_result_activation
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_forward_result_activation
#check EvmCompiler.Functions.AllocationObserverPreservation.Expr.observer_forward_result_activation
#check EvmCompiler.Locals.ObserverSemantics.primitiveSemantics_eval_vars_eq
#check EvmCompiler.Functions.AllocationObserverSafety.Expr.MemorySafeEval.vars_eq
#check EvmCompiler.Expressions.ObserverPreservation.verified
#check EvmCompiler.Locals.ObserverSemantics.eval_gas_cons
#check EvmCompiler.Locals.ObserverSemantics.eval_msize_cons
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.run
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactTerminates
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay.observed_eq_transcript
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay.remaining_eq_nil
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_gas_cons
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_msize_cons
#check EvmCompiler.TypedCfg.Effects.ofPrim_gas_observesResources
#check EvmCompiler.TypedCfg.Effects.ofPrim_msize_observesResources
#check EvmCompiler.Public.Observer.ExactReplay
#check EvmCompiler.Public.Observer.TerminalRun
#check EvmCompiler.Public.Observer.compileResourceArtifactWithPolicy?_verifiedRun
#check EvmCompiler.Simulation.ObserverPass.ForwardPreservation
#check EvmCompiler.Simulation.ObserverPass.BackwardAdequacy
#check EvmCompiler.Assembly.Preservation.stepAt_emit_result_withOracle_eq
#check EvmCompiler.Assembly.Preservation.target_runNResultWithOracle_eq_runList_of_emitInstr?
#check EvmCompiler.Assembly.Preservation.assemble_target_runNResultWithOracle_source_step_exact
#check EvmCompiler.Assembly.Preservation.compile_target_runNResultWithOracle_source_step_exact
#check EvmCompiler.Assembly.Preservation.emitted_length_le_of_terminal_target_run
#check EvmCompiler.Assembly.Program.instrAtPc_next_or_end
#check EvmCompiler.Assembly.Program.instrAtPc_of_labelPc
#check EvmCompiler.Assembly.Bytecode.assemble_fetch_byteLength_none
#check EvmCompiler.Assembly.Preservation.source_stepAtResultWithOracle_running_boundary
#check EvmCompiler.Assembly.Preservation.assemble_terminal_target_run_source_exists
#check EvmCompiler.Assembly.Preservation.compile_terminal_target_run_source_exists
#check EvmCompiler.TypedCfg.ObserverSemantics.Instr.runState
#check EvmCompiler.TypedCfg.ObserverSemantics.Block.runBody
#check EvmCompiler.TypedCfg.ObserverPreservation.Instr.lowerAt_source_runNResultWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Block.lowerBodyFrom?_source_runNResultWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle_of_direct
#check EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_eventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_positiveEventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_positiveEventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_eventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_accountsForHalt
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_terminal_backward
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.compileCertified?_entry_terminal_backward
#check EvmCompiler.Structured.TypedCfgCompiler.Shape.SourceFrameFits
#check EvmCompiler.Structured.TypedCfgCompilerFacts.Shape.sourceLength_eq_of_returnTokenDepth?_eq_some
#check EvmCompiler.Structured.TypedCfgPreservation.BasicInstr.step_sourceFrameFits_of_type
#check EvmCompiler.Structured.ObserverAdequacy.Code.sourceFrameFits
#check EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.of_at
#check EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.not_of_pushed_return
#check EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.JumpAt.of_rel
#check EvmCompiler.Structured.ObserverAdequacy.Block.adequateWithin_cons_of_compileStmtListFuel?
#check EvmCompiler.Structured.ObserverAdequacy.Call.entry_step_of_compileStmtFuel?
#check EvmCompiler.Structured.ObserverAdequacy.Call.procEntry_runN
#check EvmCompiler.Structured.ObserverAdequacy.Call.dispatch_step
#check EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithinFuel_call_of_compileStmtFuel?
#check EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithin_call_of_compileStmtFuel?
#check EvmCompiler.Structured.ObserverAdequacy.Program.generateWithProcEntryShapes?_terminal_backward
#check EvmCompiler.Assembly.Source.runNResultWithOracle_compare_halted
#check EvmCompiler.Yul.StateRelation.Replay.Rel
#check EvmCompiler.Yul.FunctionsObserverPreservation.observerPrim
#check EvmCompiler.Yul.FunctionsObserverPreservation.gas
#check EvmCompiler.Yul.FunctionsObserverPreservation.msize
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerEvalGas
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerEvalMsize
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetGas
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetMsize
#check EvmCompiler.Yul.EndToEnd.State.InitialRel
#check EvmCompiler.Yul.EndToEnd.Result.Rel
#check EvmCompiler.Yul.EndToEnd.Result.target_terminal
#check EvmCompiler.Yul.EndToEnd.ClosedArtifact
#check EvmCompiler.Yul.EndToEnd.ClosedArtifact.valid
#check EvmCompiler.Yul.EndToEnd.ClosedArtifact.observerReplay
#check EvmCompiler.Yul.EndToEnd.ClosedResourceCorrect

#print axioms EvmCompiler.Locals.ObserverSemantics.eval_gas_cons
#print axioms EvmCompiler.Functions.ObserverSemantics.stmt_run_let_gas_cons
#print axioms EvmCompiler.Functions.ObserverSemantics.runBody_let_gas_cons
#print axioms EvmCompiler.Functions.ObserverSemantics.stmt_run_call_let_gas_cons
#print axioms EvmCompiler.Functions.AllocationObserverRelation.Frame.budget_zero_of_scratchFrameConfig?
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_backward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_backward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_backward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_backward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_backward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_forward_of_compileCode
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_backward_of_compileCode
#print axioms EvmCompiler.Assembly.UInt256_ofNat_add_sub_right
#print axioms EvmCompiler.Structured.EffectSemantics.Code.run_append
#print axioms EvmCompiler.Structured.ObserverSemantics.Code.run_append
#print axioms EvmCompiler.Compiler.MemoryRelation.writeWord_memory_size_ge_end
#print axioms EvmCompiler.Compiler.MemoryRelation.writeWord_memory_size_ge
#print axioms EvmCompiler.Compiler.MemoryRelation.readWithPadding_writeWord_same_growing
#print axioms EvmCompiler.Compiler.MemoryRelation.mload_eq_lookup_of_end_le
#print axioms EvmCompiler.Compiler.MemoryRelation.mstore_end_le_activeBytes
#print axioms EvmCompiler.Compiler.MemoryRelation.mstore_activeBytes_lt_size_of_activeBytes_lt_size
#print axioms EvmCompiler.Compiler.MemoryRelation.lookupMemory_mstore_same_growing
#print axioms EvmCompiler.Compiler.MemoryRelation.readWithPadding_writeWord_disjoint_growing
#print axioms EvmCompiler.Compiler.MemoryRelation.lookupMemory_mstore_disjoint_growing
#print axioms EvmCompiler.Functions.AllocationLowering.scratchStoreExpr_compileCode
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchAssignTop_forward_live
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchAssignTop_backward_live
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchAssignTop_forward_of_storeTopSlotCode?_live
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchAssignTop_backward_of_storeTopSlotCode?_live
#print axioms EvmCompiler.Functions.AllocationObserverExpression.Expr.invariant_zero
#print axioms EvmCompiler.Functions.AllocationObserverStatement.ExprLeaf.forward_of_invariant
#print axioms EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.forward_of_invariant
#print axioms EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.forward_of_invariant
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtInvariantForward.assign_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularBlockInvariantForward.cons_regular
#print axioms EvmCompiler.Functions.AllocationLowering.lowerBlockOpen_cons_components
#print axioms EvmCompiler.Locals.Block.compileOpen_append_components
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Frame.allocatorInit_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Frame.allocatorAdvance_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Frame.framePrealloc_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameAcquire_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameAcquire_backward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameRelease_forward
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Frame.scratchFrameRelease_backward
#print axioms EvmCompiler.Functions.AllocationObserverRelation.Frame.mstore_end_le_activeBytes
#print axioms EvmCompiler.Functions.AllocationObserverRelation.Frame.noWrap_of_budget_of_scratchFrameConfig?
#print axioms EvmCompiler.Compiler.MemoryRelation.byteAt_writeWord_of_outside
#print axioms EvmCompiler.Compiler.MemoryRelation.MachineRel.mstore_target
#print axioms EvmCompiler.Compiler.MemoryRelation.lookupMemory_mstore_same
#print axioms EvmCompiler.Compiler.MemoryRelation.lookupMemory_mstore_disjoint
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ScratchStateRel.assign_scratch_live
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ScratchStateRel.assign_scratch
#print axioms EvmCompiler.Functions.AllocationObserverRelation.Frame.hostAddressable_of_budget_of_scratchFrameConfig?
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.ObserverCode.run_mstore
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_forward_scratch
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_backward_scratch
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_forward_scratch
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_backward_scratch
#print axioms EvmCompiler.Functions.AllocationObserverSafety.Expr.MemorySafeEval.eval_eq
#print axioms EvmCompiler.Functions.AllocationObserverSafety.ExprSeq.MemorySafeEval.eval_eq
#print axioms EvmCompiler.Functions.AllocationObserverContext.classify_var
#print axioms EvmCompiler.Functions.AllocationObserverExpression.PrimitiveForward.gas
#print axioms EvmCompiler.Functions.AllocationObserverExpression.PrimitiveForward.msize
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.SharedFamily.simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.SharedFamily.primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mload_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mload_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mstore_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mstore_primitiveForward
#print axioms EvmCompiler.Compiler.MemoryRelation.writeBytes_memory_data
#print axioms EvmCompiler.Compiler.MemoryRelation.lookupMemory_eq_of_writeBytes_disjoint_growing
#print axioms EvmCompiler.Compiler.MemoryRelation.MachineRel.mstore8_both
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mstore8_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mstore8_primitiveForward
#print axioms EvmCompiler.Compiler.MemoryRelation.byteAt_write_of_outside
#print axioms EvmCompiler.Compiler.MemoryRelation.byteAt_write_of_inside
#print axioms EvmCompiler.Compiler.MemoryRelation.lookupMemory_eq_of_write_disjoint_growing
#print axioms EvmCompiler.Compiler.MemoryRelation.OutsideReservation.write_self_both
#print axioms EvmCompiler.Compiler.MemoryRelation.MachineRel.copy_both
#print axioms EvmCompiler.Compiler.MemoryRelation.MachineRel.mcopy_both
#print axioms EvmCompiler.Compiler.MemoryRelation.MachineRel.readRange_both
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.copy_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.read_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.keccak256_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.keccak256_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.logOp_both
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.LogFamily.simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.LogFamily.primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.canonicalPrimitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.calldatacopy_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.calldatacopy_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.codecopy_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.codecopy_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.returndatacopy_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.returndatacopy_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.extcodecopy_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.extcodecopy_primitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mcopy_simulate
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.MemoryFamily.mcopy_primitiveForward
#print axioms EvmCompiler.Locals.Source.PrimitiveSemantics.structured_eval_step_exists
#print axioms EvmCompiler.Locals.Source.PrimitiveSemantics.structured_eval_length
#print axioms EvmCompiler.Functions.AllocationObserverExpression.forwardExpr
#print axioms EvmCompiler.Functions.AllocationObserverExpression.forwardExprSeq
#print axioms EvmCompiler.Functions.AllocationObserverExpression.Expr.backward_of_safeEval
#print axioms EvmCompiler.Functions.AllocationObserverExpression.ExprSeq.backward_of_safeEval
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.canonicalStackPrimitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverPrimitive.canonicalActivationPrimitiveForward
#print axioms EvmCompiler.Functions.AllocationObserverContext.classify_activation_var
#print axioms EvmCompiler.Functions.AllocationObserverRelation.StoreRel.rebase_prefix_stack_only
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.activeNoWrap
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ExprResultRel.append
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ScratchExprResultRel.append
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationExprResultRel.append
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_forward_result
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.literal_backward_result
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_forward_result
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.stackVar_backward_result
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_forward_result
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.scratchVar_backward_result
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_forward_result_scratch
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.gas_backward_result_scratch
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_forward_result_scratch
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.Expr.msize_backward_result_scratch
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ScratchStateRel.declare_stack_live
#print axioms EvmCompiler.Functions.AllocationObserverContext.classify_let_transition
#print axioms EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.compiler_shape
#print axioms EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.forward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.backward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.compiler_shape
#print axioms EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.forward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.backward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.Plain.forward
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.Plain.backward
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.BreakLeaf.forward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.BreakLeaf.backward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.ContinueLeaf.forward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.ContinueLeaf.backward_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.forward_activation_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.LetLeaf.backward_activation_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.forward_activation_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.AssignLeaf.backward_activation_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverTerminal.Invocation.forward_observer
#print axioms EvmCompiler.Functions.AllocationObserverStatement.TerminalLeaf.args_compiler_shape
#print axioms EvmCompiler.Functions.AllocationObserverStatement.TerminalLeaf.forward_args_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationOutcomeRel.modeRel
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationOutcomeRel.target_nonregular
#print axioms EvmCompiler.Functions.Source.Effectful.Block.runOpen_cons_regular_exists
#print axioms EvmCompiler.Functions.Source.Effectful.Block.runOpen_cons_nonregular
#print axioms EvmCompiler.Structured.EffectSemantics.Block.Eval.append_regular_exists
#print axioms EvmCompiler.Structured.EffectSemantics.Block.Eval.append_nonregular
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtForward.expr_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtForward.let_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtForward.assign_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.NonregularStmtForward.terminalArgs_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.NonregularStmtForward.brk_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.NonregularStmtForward.cont_of_compilers
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.BlockForward.nil
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.BlockForward.cons_regular
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.BlockForward.cons_nonregular
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.assign_stack_live
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.assign_scratch
#print axioms EvmCompiler.Functions.AllocationObserverPreservation.ObserverCode.run_swap_pop
#print axioms EvmCompiler.Locals.ObserverSemantics.primitiveSemantics_eval_vars_eq
#print axioms EvmCompiler.Functions.AllocationObserverSafety.Expr.MemorySafeEval.vars_eq
#print axioms EvmCompiler.Expressions.ObserverPreservation.verified
#print axioms EvmCompiler.Locals.ObserverSemantics.eval_msize_cons
#print axioms EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_gas_cons
#print axioms EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_msize_cons
#print axioms EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay.observed_eq_transcript
#print axioms EvmCompiler.Public.Observer.compileResourceArtifactWithPolicy?_verifiedRun
#print axioms EvmCompiler.Assembly.Preservation.stepAt_emit_result_withOracle_eq
#print axioms EvmCompiler.Assembly.Preservation.target_runNResultWithOracle_eq_runList_of_emitInstr?
#print axioms EvmCompiler.Assembly.Preservation.compile_target_runNResultWithOracle_source_step_exact
#print axioms EvmCompiler.Assembly.Preservation.emitted_length_le_of_terminal_target_run
#print axioms EvmCompiler.Assembly.Preservation.assemble_terminal_target_run_source_exists
#print axioms EvmCompiler.Assembly.Preservation.compile_terminal_target_run_source_exists
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Instr.lowerAt_source_runNResultWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Block.lowerBodyFrom?_source_runNResultWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle_of_direct
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_eventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_positiveEventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_positiveEventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_eventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_accountsForHalt
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_terminal_backward
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.compileCertified?_entry_terminal_backward
#print axioms EvmCompiler.Structured.TypedCfgCompilerFacts.Shape.sourceLength_eq_of_returnTokenDepth?_eq_some
#print axioms EvmCompiler.Structured.TypedCfgPreservation.BasicInstr.step_sourceFrameFits_of_type
#print axioms EvmCompiler.Structured.ObserverAdequacy.Code.sourceFrameFits
#print axioms EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.of_at
#print axioms EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.not_of_pushed_return
#print axioms EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.JumpAt.of_rel
#print axioms EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.RecursiveBoundary.pushJumpAt
#print axioms EvmCompiler.Structured.ObserverAdequacy.Generated.adequateWithinFuel_leave
#print axioms EvmCompiler.Structured.ObserverAdequacy.Generated.adequateWithinFuel_block
#print axioms EvmCompiler.Structured.ObserverAdequacy.Generated.adequateWithinFuel_stmt
#print axioms EvmCompiler.Structured.ObserverAdequacy.Program.generateWithProcEntryShapes?_terminal_backward
#print axioms EvmCompiler.Structured.ObserverAdequacy.Block.adequateWithin_cons_of_compileStmtListFuel?
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.entry_step_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.procEntry_runN
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.dispatch_step
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithinFuel_call_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithinFuel_call_of_compileStmtFuel?_protected
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithin_call_of_compileStmtFuel?
#print axioms EvmCompiler.Assembly.Source.runNResultWithOracle_compare_halted
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.observerPrim
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.gas
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.msize
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.lowerEvalGas
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetGas
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetMsize
#print axioms EvmCompiler.Functions.AllocationObserverRelation.PlanAgreesOn.symm
#print axioms EvmCompiler.Functions.AllocationObserverRelation.currentStackOrder_restrict
#print axioms EvmCompiler.Functions.AllocationObserverRelation.SameFrame.trans
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.pop_target
#print axioms EvmCompiler.Functions.AllocationObserverRelation.ActivationStateRel.transport_plan
#print axioms EvmCompiler.Functions.AllocationLowering.lowerBlockOpen_stateExtends
#print axioms EvmCompiler.Functions.AllocationObserverContext.ActivationExprContext.planAgreesOn
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.Plain.transition_of_stateExtends
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.Plain.restore_context
#print axioms EvmCompiler.Functions.AllocationObserverCleanup.Plain.forward_exact
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularScopedBlockInvariantForward.finish_regular
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtInvariantForward.block_of_components
#print axioms EvmCompiler.Functions.AllocationObserverExpression.Expr.condition_forward
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtInvariantForward.if_false_of_components
#print axioms EvmCompiler.Functions.AllocationObserverStatement.Sequence.RegularStmtInvariantForward.if_true_of_components
#print axioms EvmCompiler.Yul.EndToEnd.Result.target_terminal
#print axioms EvmCompiler.Yul.EndToEnd.ClosedArtifact.valid
#print axioms EvmCompiler.Yul.EndToEnd.ClosedArtifact.observerReplay
