import EvmCompiler.Functions.ObserverSemantics
import EvmCompiler.Locals.ObserverSemantics
import EvmCompiler.Public.Observer
import EvmCompiler.Simulation.ObserverPass
import EvmCompiler.Structured.ObserverCallAdequacy
import EvmCompiler.Structured.ObserverFrameInvariant
import EvmCompiler.Structured.ObserverSequenceAdequacy
import EvmCompiler.Yul.FunctionsObserverPreservation
import EvmCompiler.Yul.ObserverSemantics
import EvmCompiler.Yul.StateRelation
import EvmCompiler.Yul.EndToEnd
import EvmCompiler.TypedCfg.ObserverPreservation

#check EvmCompiler.Yul.Source.Effectful.StateModel
#check EvmCompiler.Yul.Source.Effectful.PrimitiveSemantics
#check EvmCompiler.Simulation.ResourceReplay.State
#check EvmCompiler.Locals.ObserverSemantics.Program.ExactReplay
#check EvmCompiler.Functions.Source.Effectful.Program.runState
#check EvmCompiler.Functions.ObserverSemantics.Program.runState
#check EvmCompiler.Functions.ObserverSemantics.stmt_run_let_gas_cons
#check EvmCompiler.Functions.ObserverSemantics.runBody_let_gas_cons
#check EvmCompiler.Functions.ObserverSemantics.stmt_run_call_let_gas_cons
#check EvmCompiler.Locals.ObserverSemantics.eval_gas_cons
#check EvmCompiler.Locals.ObserverSemantics.eval_msize_cons
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.run
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactTerminates
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay.observed_eq_transcript
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay.remaining_eq_nil
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_gas_cons
#check EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_msize_cons
#check EvmCompiler.TypedCfg.Effects.ofPrim_gas_observesResources
#check EvmCompiler.TypedCfg.Effects.ofPrim_msize_observesResources
#check EvmCompiler.Public.Observer.ExactReplay
#check EvmCompiler.Public.Observer.TerminalRun
#check EvmCompiler.Public.Observer.compileResourceArtifactWithPolicy?_verifiedRun
#check EvmCompiler.Simulation.ObserverPass.ForwardPreservation
#check EvmCompiler.Simulation.ObserverPass.BackwardAdequacy
#check EvmCompiler.Assembly.Preservation.stepAt_emit_result_withOracle_eq
#check EvmCompiler.Assembly.Preservation.target_runNResultWithOracle_eq_runList_of_emitInstr?
#check EvmCompiler.Assembly.Preservation.assemble_target_runNResultWithOracle_source_step_exact
#check EvmCompiler.Assembly.Preservation.compile_target_runNResultWithOracle_source_step_exact
#check EvmCompiler.Assembly.Preservation.emitted_length_le_of_terminal_target_run
#check EvmCompiler.Assembly.Program.instrAtPc_next_or_end
#check EvmCompiler.Assembly.Program.instrAtPc_of_labelPc
#check EvmCompiler.Assembly.Bytecode.assemble_fetch_byteLength_none
#check EvmCompiler.Assembly.Preservation.source_stepAtResultWithOracle_running_boundary
#check EvmCompiler.Assembly.Preservation.assemble_terminal_target_run_source_exists
#check EvmCompiler.Assembly.Preservation.compile_terminal_target_run_source_exists
#check EvmCompiler.TypedCfg.ObserverSemantics.Instr.runState
#check EvmCompiler.TypedCfg.ObserverSemantics.Block.runBody
#check EvmCompiler.TypedCfg.ObserverPreservation.Instr.lowerAt_source_runNResultWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Block.lowerBodyFrom?_source_runNResultWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle_of_direct
#check EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_eventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_positiveEventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_positiveEventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_eventuallyWithOracle
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_accountsForHalt
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_terminal_backward
#check EvmCompiler.TypedCfg.ObserverPreservation.Program.compileCertified?_entry_terminal_backward
#check EvmCompiler.Structured.TypedCfgCompiler.Shape.SourceFrameFits
#check EvmCompiler.Structured.TypedCfgCompilerFacts.Shape.sourceLength_eq_of_returnTokenDepth?_eq_some
#check EvmCompiler.Structured.TypedCfgPreservation.BasicInstr.step_sourceFrameFits_of_type
#check EvmCompiler.Structured.ObserverAdequacy.Code.sourceFrameFits
#check EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.of_at
#check EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.not_of_pushed_return
#check EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.JumpAt.of_rel
#check EvmCompiler.Structured.ObserverAdequacy.Block.adequateWithin_cons_of_compileStmtListFuel?
#check EvmCompiler.Structured.ObserverAdequacy.Call.entry_step_of_compileStmtFuel?
#check EvmCompiler.Structured.ObserverAdequacy.Call.procEntry_runN
#check EvmCompiler.Structured.ObserverAdequacy.Call.dispatch_step
#check EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithinFuel_call_of_compileStmtFuel?
#check EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithin_call_of_compileStmtFuel?
#check EvmCompiler.Assembly.Source.runNResultWithOracle_compare_halted
#check EvmCompiler.Yul.StateRelation.Replay.Rel
#check EvmCompiler.Yul.FunctionsObserverPreservation.observerPrim
#check EvmCompiler.Yul.FunctionsObserverPreservation.gas
#check EvmCompiler.Yul.FunctionsObserverPreservation.msize
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerEvalGas
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerEvalMsize
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetGas
#check EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetMsize
#check EvmCompiler.Yul.EndToEnd.State.InitialRel
#check EvmCompiler.Yul.EndToEnd.Result.Rel
#check EvmCompiler.Yul.EndToEnd.Result.target_terminal
#check EvmCompiler.Yul.EndToEnd.ClosedArtifact
#check EvmCompiler.Yul.EndToEnd.ClosedArtifact.valid
#check EvmCompiler.Yul.EndToEnd.ClosedArtifact.observerReplay
#check EvmCompiler.Yul.EndToEnd.ClosedResourceCorrect

#print axioms EvmCompiler.Locals.ObserverSemantics.eval_gas_cons
#print axioms EvmCompiler.Functions.ObserverSemantics.stmt_run_let_gas_cons
#print axioms EvmCompiler.Functions.ObserverSemantics.runBody_let_gas_cons
#print axioms EvmCompiler.Functions.ObserverSemantics.stmt_run_call_let_gas_cons
#print axioms EvmCompiler.Locals.ObserverSemantics.eval_msize_cons
#print axioms EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_gas_cons
#print axioms EvmCompiler.Yul.ObserverSemantics.SourceReplay.evalValues_msize_cons
#print axioms EvmCompiler.Yul.ObserverSemantics.SourceReplay.Program.ExactReplay.observed_eq_transcript
#print axioms EvmCompiler.Public.Observer.compileResourceArtifactWithPolicy?_verifiedRun
#print axioms EvmCompiler.Assembly.Preservation.stepAt_emit_result_withOracle_eq
#print axioms EvmCompiler.Assembly.Preservation.target_runNResultWithOracle_eq_runList_of_emitInstr?
#print axioms EvmCompiler.Assembly.Preservation.compile_target_runNResultWithOracle_source_step_exact
#print axioms EvmCompiler.Assembly.Preservation.emitted_length_le_of_terminal_target_run
#print axioms EvmCompiler.Assembly.Preservation.assemble_terminal_target_run_source_exists
#print axioms EvmCompiler.Assembly.Preservation.compile_terminal_target_run_source_exists
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Instr.lowerAt_source_runNResultWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Block.lowerBodyFrom?_source_runNResultWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle_of_direct
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Terminator.lowerAt?_eventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_eventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Block.lower?_positiveEventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_positiveEventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_eventuallyWithOracle
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_step_accountsForHalt
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.lower?_terminal_backward
#print axioms EvmCompiler.TypedCfg.ObserverPreservation.Program.compileCertified?_entry_terminal_backward
#print axioms EvmCompiler.Structured.TypedCfgCompilerFacts.Shape.sourceLength_eq_of_returnTokenDepth?_eq_some
#print axioms EvmCompiler.Structured.TypedCfgPreservation.BasicInstr.step_sourceFrameFits_of_type
#print axioms EvmCompiler.Structured.ObserverAdequacy.Code.sourceFrameFits
#print axioms EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.of_at
#print axioms EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.FrameMatches.not_of_pushed_return
#print axioms EvmCompiler.Structured.ObserverAdequacy.OutcomeSimulation.JumpAt.of_rel
#print axioms EvmCompiler.Structured.ObserverAdequacy.Block.adequateWithin_cons_of_compileStmtListFuel?
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.entry_step_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.procEntry_runN
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.dispatch_step
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithinFuel_call_of_compileStmtFuel?
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithinFuel_call_of_compileStmtFuel?_protected
#print axioms EvmCompiler.Structured.ObserverAdequacy.Call.adequateWithin_call_of_compileStmtFuel?
#print axioms EvmCompiler.Assembly.Source.runNResultWithOracle_compare_halted
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.observerPrim
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.gas
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.msize
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.lowerEvalGas
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetGas
#print axioms EvmCompiler.Yul.FunctionsObserverPreservation.lowerExecLetMsize
#print axioms EvmCompiler.Yul.EndToEnd.Result.target_terminal
#print axioms EvmCompiler.Yul.EndToEnd.ClosedArtifact.valid
#print axioms EvmCompiler.Yul.EndToEnd.ClosedArtifact.observerReplay
