import EvmCompiler.Verification

#check EvmCompiler.Compiler.StackArtifact.compile?_parts
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#check EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifact_child_image_embedded
#check EvmCompiler.Solidity.Frontend.Object.creationImage_embeds_deployedRuntimeImage
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackCodeArtifactIn?_byteDiff
#check EvmCompiler.Solidity.Frontend.Object.patchImmutables_compileWithImmutableValues?
#check EvmCompiler.Solidity.Frontend.Object.patchImmutables_compileWithImmutableValues?_ofCompile
#check EvmCompiler.Solidity.Frontend.Object.patchImmutables_image_compileWithImmutableValues?_ofCompile
#check EvmCompiler.Solidity.Frontend.Object.patchImmutablesAndLibraries_image_ofCompileUnlinked
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactUnlinked?_withValues_resolvesOriginal
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinished
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecode
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecode
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecodeWithCodeSuffix
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecodeWithCodeSuffix
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeWithCodeSuffix
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeOfRecursiveFrameBridgeWithCodeSuffix

#print axioms EvmCompiler.Compiler.StackArtifact.compile?_parts
#print axioms EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#print axioms EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifact_child_image_embedded
#print axioms EvmCompiler.Solidity.Frontend.Object.creationImage_embeds_deployedRuntimeImage
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackCodeArtifactIn?_byteDiff
#print axioms EvmCompiler.Solidity.Frontend.Object.patchImmutables_compileWithImmutableValues?
#print axioms EvmCompiler.Solidity.Frontend.Object.patchImmutables_compileWithImmutableValues?_ofCompile
#print axioms EvmCompiler.Solidity.Frontend.Object.patchImmutables_image_compileWithImmutableValues?_ofCompile
#print axioms EvmCompiler.Solidity.Frontend.Object.patchImmutablesAndLibraries_image_ofCompileUnlinked
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactUnlinked?_withValues_resolvesOriginal
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinished
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecode
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecode
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecodeWithCodeSuffix
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecodeWithCodeSuffix
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeWithCodeSuffix
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeOfRecursiveFrameBridgeWithCodeSuffix

#check EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_badJumpDestination
#check EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_badJumpDestination_withCodeSuffix
#check EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.runRefinesOpen_noBadJump
#check EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.runRefinesOpen_noBadJump_withCodeSuffix

#print axioms EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_badJumpDestination
#print axioms EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_badJumpDestination_withCodeSuffix
#print axioms EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.runRefinesOpen_noBadJump
#print axioms EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.runRefinesOpen_noBadJump_withCodeSuffix

#check EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.stackHeadroomCert?
#check EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_stackOverflow
#check EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_stackOverflow_withCodeSuffix
#check EvmCompiler.Assembly.GasfulBridge.RunRefinesOpenTotal
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeTotal
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeFinishedTotal
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeTerminalTotal
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeTotalWithCodeSuffix

#print axioms EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_stackOverflow
#print axioms EvmCompiler.Solidity.Frontend.VerifiedStackObjectArtifact.x_ne_stackOverflow_withCodeSuffix
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeTotal
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeFinishedTotal
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeTerminalTotal
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeTotalWithCodeSuffix
