import EvmCompiler.Verification

#check EvmCompiler.Compiler.StackArtifact.compile?_parts
#check EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#check EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#check EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifact_child_image_embedded
#check EvmCompiler.Solidity.Frontend.Object.creationImage_embeds_deployedRuntimeImage
#check EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinished
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecode
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecode
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecodeWithCodeSuffix
#check EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecodeWithCodeSuffix
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeWithCodeSuffix
#check EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeOfRecursiveFrameBridgeWithCodeSuffix

#print axioms EvmCompiler.Compiler.StackArtifact.compile?_parts
#print axioms EvmCompiler.Functions.StackRecursivePreservation.compiledProgramBodyAt
#print axioms EvmCompiler.Solidity.Frontend.Expr.resolveObjectBuiltins_memoryguard
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifactWithLinkerSymbols?_valid
#print axioms EvmCompiler.Solidity.Frontend.Object.compileVerifiedStackObjectArtifact_child_image_embedded
#print axioms EvmCompiler.Solidity.Frontend.Object.creationImage_embeds_deployedRuntimeImage
#print axioms EvmCompiler.Compiler.OpenInteractionComposition.compiledVerifiedStackObjectToRawBytecode
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecode
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeFinished
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecode
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecode
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToRawBytecodeWithCodeSuffix
#print axioms EvmCompiler.Solidity.RawAst.optimizedRawSolcIrToGasfulRawBytecodeWithCodeSuffix
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToRawBytecodeWithCodeSuffix
#print axioms EvmCompiler.Yul.EndToEnd.optimizedSolcYulToGasfulRawBytecodeOfRecursiveFrameBridgeWithCodeSuffix
